import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.105.0';

const supabase = createClient('https://oimiygdkrnsjzlivwafs.supabase.co','sb_publishable_WKPV0lAUCl1Lr53UujCR3g_zlQay4DS');
const day = new Date().toISOString().slice(0,10);
const key = 'solar-team-online-v1';
const seed = {people:[],fields:['North','South'],workTypes:['Установка солнечных панелей','Затяжка болтов','Подготовка кронштейнов'],teams:[]};
let db=structuredClone(seed),user=null,screen='today',selected=null,saving=false,ready=false,version=-1,accessMessage='',members=[];

function readLocal(){try{return normalise(JSON.parse(localStorage.getItem(key))||seed)}catch{return normalise(seed)}}
function normalise(data){const next={...seed,...(data||{})};next.people=Array.isArray(next.people)?next.people:[];next.fields=Array.isArray(next.fields)?next.fields:seed.fields;next.workTypes=Array.isArray(next.workTypes)?next.workTypes:seed.workTypes;next.teams=Array.isArray(next.teams)?next.teams:[];next.people.forEach(p=>p.availability||(p.availability='ON_SITE'));next.teams.forEach(t=>{if(!('to' in t))t.to=null});return next}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function acceptRow(row){db=normalise(row.data);version=row.version;ready=true;accessMessage=''}
async function change(kind,item,expected={}){if(!ready||saving)return false;saving=true;const actor=user.id;try{const {data,error}=await supabase.rpc('solar_change',{kind,item,expected});if(error)throw error;if(user?.id!==actor)return false;acceptRow(data);return true}catch(error){toast(error.code==='40001'?'Запись уже изменил коллега. Обновите страницу и повторите.':'Не сохранено: '+error.message);return false}finally{saving=false}}
async function loadCloud(currentUser){user=currentUser;ready=false;accessMessage='Загрузка Solar Team…';render();try{const {data,error}=await supabase.from('solar_shared').select('*').eq('id',1).maybeSingle();if(error)throw error;if(!data){accessMessage='Доступ по приглашению. Попросите коллегу добавить '+user.email+' в Settings → Team access.';render();return}let row=data;if(!row.initialized){const result=await supabase.rpc('solar_change',{kind:'initialize',item:readLocal(),expected:{}});if(result.error)throw result.error;row=result.data}acceptRow(row);render()}catch(error){accessMessage='Не удалось загрузить Solar Team: '+error.message;render()}}
async function refreshShared(){if(!user||!ready||saving||document.hidden||!['today','people','history','settings'].includes(screen)||document.activeElement?.matches('input,textarea,select'))return;const actor=user.id,{data,error}=await supabase.from('solar_shared').select('*').eq('id',1).maybeSingle();if(user?.id!==actor||saving||!['today','people','history','settings'].includes(screen))return;if(error){setSyncLabel('Нет соединения — повторяем');return}if(!data){ready=false;accessMessage='Доступ к Solar Team отключён.';db=structuredClone(seed);render();return}if(data.version>version){acceptRow(data);render()}setSyncLabel('Общие данные · обновляются автоматически')}
function setSyncLabel(text){const label=document.getElementById('sync-status');if(label)label.textContent=text}
setInterval(refreshShared,5000);window.addEventListener('focus',refreshShared);window.addEventListener('online',refreshShared);

const labels={NOT_STARTED:'Не начато',IN_PROGRESS:'В работе',COMPLETED:'Завершено',PARTIALLY_COMPLETED:'Частично',PROBLEM:'Проблема',NOT_COMPLETED:'Не выполнено'};
const $=s=>document.querySelector(s),person=id=>db.people.find(p=>p.id===id),isRow=v=>Number.isInteger(Number(v))&&Number(v)>=0;
const actualRows=t=>isRow(t.to)&&Number(t.to)>=Number(t.from)?Number(t.to)-Number(t.from)+1:0;
const rangeText=t=>isRow(t.to)?t.from+'–'+t.to:t.from+'–…';
function statusClass(s){return {NOT_STARTED:'notstarted',IN_PROGRESS:'inprogress',COMPLETED:'completed',PARTIALLY_COMPLETED:'partial',PROBLEM:'problem',NOT_COMPLETED:'notcompleted'}[s]||'notstarted'}
function availabilityText(s){return s==='SICK'?'Болеет':s==='OFF'?'Off':'На объекте'}
function availabilityClass(s){return s==='SICK'?'problem':s==='OFF'?'notstarted':'completed'}
function initials(p){return p.name.split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,2)}
function header(title,back){return '<header class="top">'+(back?'<button class="back" onclick="goBack()" aria-label="Назад">‹</button>':'<div class="brand"><span>☀</span> SOLAR TEAM</div>')+'<div class="date">'+new Intl.DateTimeFormat('ru',{weekday:'short',day:'numeric',month:'short'}).format(new Date(day+'T12:00:00'))+'</div></header>'+(title?'<h1>'+esc(title)+'</h1>':'')}
function nav(){return '<nav class="bottom"><button class="'+(screen==='today'?'active':'')+'" onclick="goToday()"><b>▣</b>Сегодня</button><button class="'+(screen==='people'?'active':'')+'" onclick="goPeople()"><b>♙</b>Люди</button><button class="'+(screen==='history'?'active':'')+'" onclick="goHistory()"><b>◷</b>История</button><button class="'+(screen==='settings'?'active':'')+'" onclick="goSettings()"><b>⚙</b>Настройки</button></nav>'}
function card(t){const people=t.members.map(person).filter(Boolean),rows=actualRows(t);return '<button class="card team-card" onclick="openTeam(\''+t.id+'\')"><div class="row"><h3>Команда '+t.number+'</h3><span class="tag '+statusClass(t.status)+'">'+labels[t.status]+'</span></div><div class="members">'+people.slice(0,4).map(p=>'<span class="avatar">'+initials(p)+'</span>').join('')+'<span class="more">'+people.map(p=>esc(p.name.split(' ')[0])).join(' · ')+'</span></div><div class="facts"><span>⌖ '+esc(t.field)+'</span><span>⚒ '+esc(t.work)+'</span><span>☷ '+rangeText(t)+'</span></div><div class="progress-head">Факт: <b>'+rows+' ряд.</b></div></button>'}
function auth(){return '<header class="top"><div class="brand"><span>☀</span> SOLAR TEAM</div><div class="date">Общее пространство</div></header><section class="card"><h1>Вход</h1><form onsubmit="login(event)"><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Пароль<input name="password" type="password" required minlength="6" autocomplete="current-password"></label><button class="primary">Войти</button></form></section>'}
function draw(html){$('#app').innerHTML=html+'<p id="sync-status" class="sub" style="margin-top:16px">Общие данные · обновляются автоматически</p>'+nav()}
function render(){if(!user){$('#app').innerHTML=auth();return}if(!ready){$('#app').innerHTML=header('Solar Team')+'<div class="card"><p>'+esc(accessMessage)+'</p><button class="primary" onclick="retryAccess()">Проверить доступ</button><button class="secondary" onclick="logout()">Выйти</button></div>';return}({today:drawToday,people:drawPeople,history:drawHistory,settings:drawSettings,form:drawForm,team:drawTeam,person:drawPerson,personNew:drawPersonNew,workTypes:drawWorkTypes,fields:drawFields}[screen]||drawToday)()}
function drawToday(){const teams=db.teams.filter(t=>t.date===day),rows=teams.reduce((n,t)=>n+actualRows(t),0),count=new Set(teams.flatMap(t=>t.members)).size;draw(header('')+'<h1>Сегодня</h1><p class="sub">'+teams.length+' команд · '+count+' человек · факт '+rows+' ряд.</p><section class="team-list">'+(teams.map(card).join('')||'<div class="empty">Команд пока нет.</div>')+'</section><button class="primary" onclick="newTeam()">＋ Новая команда</button>')}
function memberChips(selectedIds,includeInactive=false){return db.people.filter(p=>(p.active&&p.availability==='ON_SITE')||(includeInactive&&selectedIds.includes(p.id))).map(p=>'<label class="chip"><input type="checkbox" name="member" value="'+p.id+'" '+(selectedIds.includes(p.id)?'checked':'')+'> '+esc(p.name.split(' ')[0])+'</label>').join('')}
function options(values,current){return values.map(v=>'<option '+(v===current?'selected':'')+'>'+esc(v)+'</option>').join('')}
function drawForm(){draw(header('Создать команду',true)+'<form onsubmit="createTeam(event)"><h2>Состав команды</h2><p class="sub">Off и заболевшие скрыты.</p><div class="chips">'+memberChips([])+'</div><h2>Работа</h2><label>Участок<select name="field">'+options(db.fields)+'</select></label><label>Вид работы<select name="work">'+options(db.workTypes)+'</select></label><label>Начальный ряд<input name="from" type="number" required min="0" placeholder="Например, 120"></label><p class="sub">Конечный ряд внесёте по факту выполнения.</p><button class="primary">Создать команду</button></form>')}
function drawTeam(){const t=db.teams.find(x=>x.id===selected);if(!t){goToday();return}draw(header('Команда '+t.number,true)+'<form onsubmit="saveTeam(event,\''+t.id+'\')"><label>Дата<input name="date" type="date" required value="'+esc(t.date)+'"></label><h2>Состав команды</h2><div class="chips">'+memberChips(t.members,true)+'</div><label>Участок<select name="field">'+options(db.fields,t.field)+'</select></label><label>Вид работы<select name="work">'+options(db.workTypes,t.work)+'</select></label><div class="grid2"><label>Начали с ряда<input name="from" type="number" required min="0" value="'+t.from+'"></label><label>Завершили на ряду<input name="to" type="number" min="0" value="'+(t.to??'')+'" placeholder="По факту"></label></div><p class="sub">Фактически выполнено: <b>'+actualRows(t)+' ряд.</b></p><label>Статус<select name="status">'+Object.keys(labels).map(s=>'<option value="'+s+'" '+(s===t.status?'selected':'')+'>'+labels[s]+'</option>').join('')+'</select></label><label>Примечание<textarea name="note">'+esc(t.note)+'</textarea></label><button class="primary">Сохранить изменения</button><button type="button" class="secondary" onclick="closeTeam(\''+t.id+'\')">'+(t.closed?'Открыть команду снова':'Закрыть и сохранить в истории')+'</button></form>')}
function peopleRows(list){return list.map(p=>'<button class="person" onclick="openPerson(\''+p.id+'\')"><span class="avatar">'+initials(p)+'</span><span><b>'+esc(p.name)+'</b><br><small class="sub">'+esc(p.role)+(p.active?'':' · неактивен')+'</small></span><span class="tag '+availabilityClass(p.availability)+'">'+availabilityText(p.availability)+'</span></button>').join('')||'<div class="empty">Людей нет.</div>'}
function drawPeople(){draw(header('Люди')+'<input class="search" placeholder="⌕ Поиск…" oninput="searchPeople(this.value)"><div class="card list-card" id="personList">'+peopleRows(db.people)+'</div><button class="primary" onclick="addPerson()">＋ Добавить человека</button>')}
function personForm(p,isNew){return '<form onsubmit="'+(isNew?'createPerson(event)':'savePerson(event,\''+p.id+'\')')+'"><label>Имя и фамилия<input name="name" required value="'+esc(p.name)+'"></label><label>Должность<input name="role" required value="'+esc(p.role)+'"></label><label>Статус<select name="availability"><option value="ON_SITE" '+(p.availability==='ON_SITE'?'selected':'')+'>На объекте</option><option value="OFF" '+(p.availability==='OFF'?'selected':'')+'>Off</option><option value="SICK" '+(p.availability==='SICK'?'selected':'')+'>Болеет</option></select></label><label class="chip"><input type="checkbox" name="active" '+(p.active?'checked':'')+'> Активный сотрудник</label><button class="primary">'+(isNew?'Добавить':'Сохранить')+'</button></form>'}
function drawPerson(){const p=person(selected);if(!p){goPeople();return}draw(header('Карточка сотрудника',true)+personForm(p,false))}
function drawPersonNew(){draw(header('Новый сотрудник',true)+personForm({name:'',role:'Installer',availability:'ON_SITE',active:true},true))}
function drawHistory(){const groups={};db.teams.forEach(t=>(groups[t.date]??=[]).push(t));draw(header('История')+'<div class="card list-card">'+Object.keys(groups).sort().reverse().map(d=>'<button class="history" onclick="showHistory(\''+d+'\')"><div class="row"><b>'+d+'</b><span>›</span></div><p class="sub">'+groups[d].length+' команд · факт '+groups[d].reduce((n,t)=>n+actualRows(t),0)+' ряд.</p></button>').join('')+'</div>')}
function drawSettings(){draw(header('Настройки')+'<div class="card settings"><button onclick="editFields()">⌖ <span><b>Участки</b><br><small class="sub">'+db.fields.map(esc).join(', ')+'</small></span></button><button onclick="editWorkTypes()">⚒ <span><b>Виды работ</b><br><small class="sub">'+db.workTypes.map(esc).join(', ')+'</small></span></button><button onclick="goPeople()">♙ <span><b>Люди и должности</b><br><small class="sub">Добавление и редактирование</small></span></button></div><section class="card"><h2>Общее пространство</h2><p class="sub">У всех аккаунтов одинаковые права.</p><p>'+esc(user.email)+'</p><button class="secondary" onclick="showAccess()">Доступ команды</button><div id="access-panel"></div></section><button class="secondary" onclick="logout()">Выйти</button>')}
function listEditor(title,values,handler){draw(header(title,true)+'<form onsubmit="'+handler+'(event)"><label>Каждое значение с новой строки<textarea name="values" required style="min-height:220px">'+esc(values.join('\n'))+'</textarea></label><p class="sub">Удалите строку, чтобы убрать значение из выбора для новых команд. История сохранит прежнее название.</p><button class="primary">Сохранить справочник</button></form>')}
function drawWorkTypes(){listEditor('Виды работ',db.workTypes,'saveWorkTypes')}
function drawFields(){listEditor('Участки',db.fields,'saveFields')}

window.showAccess=async()=>{const {data,error}=await supabase.from('solar_members').select('email').order('added_at');if(error){toast(error.message);return}members=data;const panel=$('#access-panel');if(panel)panel.innerHTML='<h2>Аккаунты с доступом</h2>'+members.map(m=>'<p>'+esc(m.email)+' · полный доступ</p>').join('')};
window.retryAccess=()=>loadCloud(user);window.goBack=()=>{if(['person','personNew'].includes(screen))goPeople();else if(['workTypes','fields'].includes(screen))goSettings();else goToday()};
window.goToday=()=>{screen='today';selected=null;render()};window.goPeople=()=>{screen='people';selected=null;render()};window.goHistory=()=>{screen='history';selected=null;render()};window.goSettings=()=>{screen='settings';selected=null;render()};
window.newTeam=()=>{screen='form';render()};window.openTeam=id=>{selected=id;screen='team';render()};window.openPerson=id=>{selected=id;screen='person';render()};window.addPerson=()=>{screen='personNew';render()};window.editWorkTypes=()=>{screen='workTypes';render()};window.editFields=()=>{screen='fields';render()};
window.createTeam=async e=>{e.preventDefault();if(saving)return;const f=new FormData(e.target),from=Number(f.get('from')),ids=f.getAll('member');if(!ids.length||!isRow(from)){toast('Выберите людей и укажите начальный ряд.');return}const t={id:crypto.randomUUID(),date:day,members:ids,field:f.get('field'),work:f.get('work'),from,to:null,status:'IN_PROGRESS',note:'',closed:false};if(await change('add_team',t))openTeam(t.id)};
window.saveTeam=async(e,id)=>{e.preventDefault();if(saving)return;const t=db.teams.find(x=>x.id===id),f=new FormData(e.target),from=Number(f.get('from')),rawTo=f.get('to').trim(),to=rawTo===''?null:Number(rawTo),teamMembers=f.getAll('member');if(!teamMembers.length||!isRow(from)||(to!==null&&(!isRow(to)||to<from))){toast('Проверьте состав и диапазон рядов.');return}const patch={date:f.get('date'),members:teamMembers,field:f.get('field'),work:f.get('work'),from,to,status:f.get('status'),note:f.get('note')};const item={id},expected={};for(const [k,v] of Object.entries(patch)){if(JSON.stringify(t[k])!==JSON.stringify(v)){item[k]=v;expected[k]=t[k]??null}}if(Object.keys(item).length===1){toast('Изменений нет');return}if(await change('team_patch',item,expected)){render();toast('Сохранено для всех')}};
window.closeTeam=async id=>{const t=db.teams.find(x=>x.id===id),item={id,closed:!t.closed},expected={closed:t.closed};if(!t.closed&&t.to==null){toast('Сначала укажите конечный ряд по факту.');return}if(!t.closed&&['NOT_STARTED','IN_PROGRESS'].includes(t.status)){item.status='COMPLETED';expected.status=t.status}if(await change('team_patch',item,expected)){render();toast(t.closed?'Команда снова открыта':'Сохранено в истории')}};
window.createPerson=async e=>{e.preventDefault();const f=new FormData(e.target),item={id:crypto.randomUUID(),name:f.get('name').trim(),role:f.get('role').trim(),availability:f.get('availability'),active:f.get('active')==='on'};if(!item.name||!item.role){toast('Введите имя и должность.');return}if(await change('add_person',item)){goPeople();toast('Сотрудник добавлен')}};
window.savePerson=async(e,id)=>{e.preventDefault();const p=person(id),f=new FormData(e.target),patch={name:f.get('name').trim(),role:f.get('role').trim(),availability:f.get('availability'),active:f.get('active')==='on'};if(!patch.name||!patch.role){toast('Введите имя и должность.');return}const item={id},expected={};for(const [k,v] of Object.entries(patch)){if(p[k]!==v){item[k]=v;expected[k]=p[k]}}if(Object.keys(item).length===1){toast('Изменений нет');return}if(await change('person_patch',item,expected)){render();toast('Сотрудник обновлён')}};
function cleanList(value){return [...new Set(value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean))]}
async function saveList(e,key){e.preventDefault();const values=cleanList(new FormData(e.target).get('values'));if(!values.length){toast('Оставьте хотя бы одно значение.');return}if(await change('settings_patch',{[key]:values},{[key]:db[key]})){goSettings();toast('Справочник обновлён')}}
window.saveWorkTypes=e=>saveList(e,'workTypes');window.saveFields=e=>saveList(e,'fields');
window.searchPeople=q=>{$('#personList').innerHTML=peopleRows(db.people.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())||p.role.toLowerCase().includes(q.toLowerCase())))};
window.showHistory=date=>{screen='historyDetail';draw(header('История',true)+'<h1>'+date+'</h1><section class="team-list">'+db.teams.filter(t=>t.date===date).map(card).join('')+'</section>')};
window.login=async e=>{e.preventDefault();const f=new FormData(e.target),{data,error}=await supabase.auth.signInWithPassword({email:f.get('email').trim(),password:f.get('password')});if(error){toast(error.message);return}await loadCloud(data.user);if(ready)toast('Solar Team загружен')};
window.logout=async()=>{if(saving){toast('Дождитесь сохранения.');return}const {error}=await supabase.auth.signOut();if(error){toast(error.message);return}user=null;ready=false;version=-1;db=structuredClone(seed);screen='today';selected=null;members=[];render()};
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),8000)}

(async()=>{const {data:{session}}=await supabase.auth.getSession();if(session)await loadCloud(session.user);else render()})();
