import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.105.0';

const supabase = createClient('https://oimiygdkrnsjzlivwafs.supabase.co','sb_publishable_WKPV0lAUCl1Lr53UujCR3g_zlQay4DS');
const defaultJobGroups=['Team Leads','Technicians','Mechanics'];
const seed = {people:[],fields:['North','South'],workTypes:['Solar panel installation','Bolt tightening','Bracket preparation'],jobGroups:defaultJobGroups,archivedJobGroups:[],teams:[],assignmentHistory:[]};
const weatherSite={name:'P223_Nagbøl',place:'Solar Park Nagbøl',address:'Nagbølvej 83A, 6640 Lunderskov'};
const weatherCacheKey='solar-team-dmi-weather-v2', weatherFreshMs=10*60*1000, weatherMaxStaleMs=6*60*60*1000;
let db=structuredClone(seed), user=null, ready=false, saving=false, version=-1;
let screen='today', selected=null, origin='today', dirty=false, snapshot=null, accessMessage='', syncText='Connecting…';
let directory='workTypes', directoryIndex=-1, pendingId=null, staffingMode='teams', createMembers=[], createBack='today', createTemplate=null, createUnavailable=[], personBack='people';
let weather={status:'idle',data:null,fetchedAt:0,error:''}, weatherLoading=false;
let peopleFilter={query:'',active:'active',availability:'',assignment:'',jobGroup:'',grouped:false}, historyFilter={date:'',field:'',work:'',person:''};
let photoUrls=new Map(), pendingPhotoFile=null, pendingPhotoPreview='', removePhotoRequested=false;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDay=(date=new Date())=>[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');
const isRow=v=>v!==null&&v!==undefined&&String(v).trim()!==''&&Number.isSafeInteger(Number(v))&&Number(v)>=0&&Number(v)<=2147483647;
const actualRows=t=>isRow(t.from)&&isRow(t.to)&&Number(t.to)>=Number(t.from)?Number(t.to)-Number(t.from)+1:0;
const rangeText=t=>isRow(t.to)?'Rows '+t.from+'–'+t.to:'Start row '+t.from;
const person=id=>db.people.find(p=>p.id===id);
const team=id=>db.teams.find(t=>t.id===id);
const labels={NOT_STARTED:'Not started',IN_PROGRESS:'In progress',COMPLETED:'Completed',PARTIALLY_COMPLETED:'Partially completed',PROBLEM:'Problem',NOT_COMPLETED:'Not completed'};
const availabilityText=s=>s==='SICK'?'Sick':s==='OFF'?'Off':'On site';
const initials=p=>p.name.split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,2);
const avatar=(p,size='')=>{const url=photoUrls.get(p.id);return '<span class="avatar '+esc(size)+'">'+(url?'<img src="'+esc(url)+'" alt="">':esc(initials(p)))+'</span>'};
const statusClass=s=>({COMPLETED:'good',IN_PROGRESS:'blue',PROBLEM:'bad',NOT_COMPLETED:'bad',PARTIALLY_COMPLETED:'amber',SICK:'bad',OFF:'amber',ON_SITE:'good'}[s]||'neutral');
const tag=(text,s)=>'<span class="tag '+statusClass(s)+'">'+esc(text)+'</span>';
const dateLabel=d=>new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
const btn=(label,action,cls='secondary',id='')=>'<button type="button" class="'+cls+'" data-action="'+action+'" data-id="'+esc(id)+'">'+label+'</button>';
const weatherNumber=(value,min,max)=>{const number=Number(value);return Number.isFinite(number)&&number>=min&&number<=max?number:null};
function normaliseWeather(value){const source=value?.weather||value||{},temperatureC=weatherNumber(source.temperatureC,-80,60),humidityPct=weatherNumber(source.humidityPct,0,100),windSpeedMs=weatherNumber(source.windSpeedMs,0,100),windDirectionDeg=weatherNumber(source.windDirectionDeg,0,360),observedAt=Date.parse(source.observedAt||source.forecastAt),precipitationMm=source.precipitationMm==null?null:weatherNumber(source.precipitationMm,0,1000),precipitationHours=source.precipitationHours==null?null:weatherNumber(source.precipitationHours,1,48);return temperatureC===null||humidityPct===null||windSpeedMs===null||windDirectionDeg===null||!Number.isFinite(observedAt)?null:{temperatureC,humidityPct,windSpeedMs,windDirectionDeg,forecastAt:new Date(observedAt).toISOString(),precipitationMm,precipitationHours}}
function windCompass(degrees){const points=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'];return points[Math.round(((Number(degrees)%360)+360)%360/22.5)%16]}
const weatherTime=value=>new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const weatherIcons={temperature:'<path d="M9 14.5V5a3 3 0 0 1 6 0v9.5a5 5 0 1 1-6 0Z"/><path d="M12 7v9"/>',wind:'<path d="M3 8h11a3 3 0 1 0-3-3"/><path d="M3 12h15a3 3 0 1 1-3 3"/><path d="M3 16h7"/>',humidity:'<path d="M12 2.8S6 9.2 6 14a6 6 0 0 0 12 0c0-4.8-6-11.2-6-11.2Z"/><path d="M9.5 15.5a3 3 0 0 0 4.5 1.7"/>',rain:'<path d="M7 17a4 4 0 0 1-.5-8A6 6 0 0 1 18 10a3.5 3.5 0 0 1-1 7"/><path d="m9 19-1 2m5-2-1 2m5-2-1 2"/>',birthday:'<path d="M4 10h16v11H4zM3 10h18M8 10v11M16 10v11"/><path d="M12 10V6M12 6c-3 0-4-1.3-4-2.5S9.2 2 10 2c1.5 0 2 2.3 2 4Zm0 0c3 0 4-1.3 4-2.5S14.8 2 14 2c-1.5 0-2 2.3-2 4Z"/>'};
const weatherIcon=name=>'<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+weatherIcons[name]+'</svg>';
function weatherCard(){const data=weather.data,busy=weather.status==='loading';if(!data)return '<section id="weather-card" class="card weather-card" aria-labelledby="weather-title"><div class="weather-head"><div><p class="eyebrow">Site weather</p><h2 id="weather-title">'+esc(weatherSite.name)+'</h2><p class="site-address">'+esc(weatherSite.place)+' · '+esc(weatherSite.address)+'</p></div><span class="weather-source">DMI</span></div>'+(weather.status==='error'?'<div class="weather-message" role="status"><strong>Weather is unavailable</strong><span>'+esc(weather.error||'Try again in a moment.')+'</span></div>'+btn('Try again','weather','compact'):'<div class="weather-loading" role="status"><span class="spinner" aria-hidden="true"></span><span>Loading site weather…</span></div>')+'</section>';
const stale=weather.status==='stale',rain=data.precipitationMm==null?'—':data.precipitationMm.toFixed(1),rainLabel=data.precipitationHours?'Rain · next '+data.precipitationHours+'h':'Rain forecast unavailable';return '<section id="weather-card" class="card weather-card" aria-labelledby="weather-title"><div class="weather-head"><div><p class="eyebrow">Site weather</p><h2 id="weather-title">'+esc(weatherSite.name)+'</h2><p class="site-address">'+esc(weatherSite.place)+' · '+esc(weatherSite.address)+'</p></div><span class="weather-source">DMI</span></div><div class="weather-grid"><div class="weather-metric"><span class="weather-symbol">'+weatherIcon('temperature')+'</span><span><strong>'+data.temperatureC.toFixed(1)+' °C</strong><small>Temperature</small></span></div><div class="weather-metric"><span class="weather-symbol">'+weatherIcon('wind')+'</span><span><strong>'+data.windSpeedMs.toFixed(1)+' m/s</strong><small>Wind · '+windCompass(data.windDirectionDeg)+' '+Math.round(data.windDirectionDeg)+'°</small></span></div><div class="weather-metric"><span class="weather-symbol">'+weatherIcon('humidity')+'</span><span><strong>'+Math.round(data.humidityPct)+'%</strong><small>Humidity</small></span></div><div class="weather-metric"><span class="weather-symbol">'+weatherIcon('rain')+'</span><span><strong>'+rain+' mm</strong><small>'+rainLabel+'</small></span></div></div><div class="weather-footer"><small>'+(stale?'Last available observation':'Observed')+' at '+weatherTime(data.forecastAt)+(stale?' · '+esc(weather.error):'')+'</small>'+btn(busy?'Refreshing…':'Refresh','weather','compact')+'</div></section>'}
function normalise(data){const next={...structuredClone(seed),...(data||{})};for(const k of ['people','fields','workTypes','jobGroups','archivedJobGroups','teams','assignmentHistory'])if(!Array.isArray(next[k]))next[k]=structuredClone(seed[k]);next.people=next.people.map(p=>({...p,jobGroup:typeof p.jobGroup==='string'?p.jobGroup:'',photoPath:typeof p.photoPath==='string'?p.photoPath:'',birthDate:typeof p.birthDate==='string'?p.birthDate:''}));next.teams=next.teams.map(t=>({...t,issueResolved:Boolean(t.issueResolved)}));return next}
function birthdayDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const [year,month,day]=value.split('-').map(Number),date=new Date(year,month-1,day,12);return date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day}
const birthdayLabel=value=>new Intl.DateTimeFormat('en',{day:'numeric',month:'long',year:'numeric'}).format(new Date(value+'T12:00:00'));
function birthdaysToday(date=new Date()){const key=String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');return db.people.filter(p=>p.active&&birthdayDate(p.birthDate)&&p.birthDate.slice(5)===key)}
function birthdayBanner(){const people=birthdaysToday();if(!people.length)return '';return '<section class="birthday-banner" role="status"><span class="birthday-icon">'+weatherIcon('birthday')+'</span><div><strong>Birthday today</strong><p>'+people.map(p=>esc(p.name)).join(' · ')+'</p></div></section>'}
function acceptRow(row){db=normalise(row.data);version=row.version;ready=true;syncText='Shared data · Up to date'}
function assignments(id){return db.teams.filter(t=>t.date===localDay()&&!t.closed&&t.members.includes(id))}
function assignmentConflicts(ids,date=localDay(),exclude=''){return db.teams.filter(t=>t.id!==exclude&&t.date===date&&!t.closed&&t.members.some(id=>ids.includes(id)))}
function totals(teams){const grouped=new Map();for(const t of teams){if(isRow(t.to))grouped.set(t.work,(grouped.get(t.work)||0)+actualRows(t))}return [...grouped]}
function staffing(){const today=db.teams.filter(t=>t.date===localDay()),ids=new Set(today.filter(t=>!t.closed).flatMap(t=>t.members)),active=db.people.filter(p=>p.active);return {teams:today.length,assigned:ids.size,available:active.filter(p=>(p.availability||'ON_SITE')==='ON_SITE'&&!ids.has(p.id)).length,off:active.filter(p=>p.availability==='OFF').length,sick:active.filter(p=>p.availability==='SICK').length,active:active.length}}
function options(values,current='',all=''){const choices=[...new Set(values)];if(current&&!choices.includes(current))choices.unshift(current);return (all?'<option value="">'+esc(all)+'</option>':'')+choices.map(v=>'<option value="'+esc(v)+'" '+(v===current?'selected':'')+'>'+esc(v)+'</option>').join('')}
function header(title,back=false){return '<header class="top">'+(back?btn('‹ <span>Back</span>','back','back'):'<div class="brand"><span aria-hidden="true">☀</span> SOLAR TEAM</div>')+'<time datetime="'+localDay()+'">'+dateLabel(localDay())+'</time></header><h1 tabindex="-1">'+esc(title)+'</h1>'}
const iconShapes={
today:'<rect x="3" y="4" width="18" height="17" rx="2"/><path d="M8 2v4M16 2v4M3 10h18"/><path d="M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/>',
people:'<circle cx="8" cy="8" r="3"/><circle cx="16" cy="8" r="3"/><path d="M2.5 20a5.5 5.5 0 0 1 11 0M10.5 20a5.5 5.5 0 0 1 11 0"/>',
history:'<path d="M3 12a9 9 0 1 0 3-6.7M3 3v5h5M12 7v5l3 2"/>',
settings:'<path d="M4 21V14M4 10V3M12 21V12M12 8V3M20 21V16M20 12V3M1 14h6M9 8h6M17 16h6"/>'};
function icon(k){return '<svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+iconShapes[k]+'</svg>'}
function nav(){const active=screen==='staffing'?'today':['person','personEdit','personNew'].includes(screen)?'people':['directory','directoryEdit'].includes(screen)?'settings':['team','teamEdit','record'].includes(screen)?origin:screen;return '<nav class="bottom" aria-label="Main navigation">'+['today','people','history','settings'].map(k=>'<button data-action="nav" data-id="'+k+'" '+(active===k?'aria-current="page"':'')+'>'+icon(k)+'<span>'+k[0].toUpperCase()+k.slice(1)+'</span></button>').join('')+'</nav>'}
function draw(content){$('#app').innerHTML=content+'<div id="feedback" role="alert" tabindex="-1" hidden></div><p id="sync-status" class="sync" role="status">'+esc(syncText)+'</p>'+nav();dirty=false}
function empty(title,text,action=''){return '<section class="empty"><h2>'+esc(title)+'</h2><p>'+esc(text)+'</p>'+action+'</section>'}
function render(focus=false){if(!user){drawAuth();return}if(!ready){$('#app').innerHTML=header('Shared workspace')+'<section class="card"><p role="status">'+esc(accessMessage)+'</p>'+btn('Retry','retry','primary')+btn('Sign out','logout')+'</section>';return}
({today:drawToday,staffing:drawStaffing,people:drawPeople,history:drawHistory,settings:drawSettings,create:drawCreate,team:drawTeam,teamEdit:drawTeamEdit,record:drawRecord,person:drawPerson,personEdit:drawPersonEdit,personNew:drawPersonEdit,directory:drawDirectory,directoryEdit:drawDirectoryEdit}[screen]||drawToday)();
if(focus){window.scrollTo(0,0);$('h1')?.focus({preventScroll:true})}}
function navigate(next,id=null,force=false){if(saving)return;if(!force&&dirty&&!window.confirm('Discard unsaved changes?'))return;
if(['today','history','staffing'].includes(screen)&&next==='team')origin=screen;
if(!['personEdit','personNew'].includes(next)){if(pendingPhotoPreview)URL.revokeObjectURL?.(pendingPhotoPreview);pendingPhotoFile=null;pendingPhotoPreview='';removePhotoRequested=false}
screen=next;selected=id;snapshot=null;pendingId=null;render(true)}
function goBack(){const back={staffing:'today',create:createBack,team:origin,teamEdit:'team',record:'team',person:personBack,personEdit:'person',personNew:'people',directory:'settings',directoryEdit:'directory'};navigate(back[screen]||'today',selected)}
function card(t){const names=t.members.map(person).filter(Boolean).map(p=>p.name);return '<button class="card team-card" data-action="team" data-id="'+esc(t.id)+'"><div class="row"><h3>Team '+esc(t.number)+'</h3>'+tag(t.closed?'Closed':labels[t.status]||t.status,t.status)+'</div><p class="work">'+esc(t.work)+'</p><p class="muted">'+esc(t.field)+' · '+names.length+' people</p><p class="member-names">'+esc(names.join(' · '))+'</p><div class="range"><span>'+esc(rangeText(t))+'</span><strong>'+ (isRow(t.to)?actualRows(t)+' rows':'Not recorded yet')+'</strong></div></button>'}
function historyCard(t){const ids=[...new Set([...t.members,...db.assignmentHistory.filter(a=>a.teamId===t.id).map(a=>a.employeeId)])],names=ids.map(person).filter(Boolean).map(p=>p.name);return '<button class="card team-card" data-action="team" data-id="'+esc(t.id)+'"><div class="row"><h3>Team '+esc(t.number)+'</h3>'+tag(t.closed?'Closed':labels[t.status]||t.status,t.status)+'</div><p class="work">'+esc(t.work)+'</p><p class="muted">'+esc(t.field)+' · '+names.length+' people</p><p class="member-names">'+esc(names.join(' · '))+'</p><div class="range"><span>'+esc(rangeText(t))+'</span><strong>'+ (isRow(t.to)?actualRows(t)+' rows':'Not recorded yet')+'</strong></div></button>'}
function summary(teams){const list=totals(teams);return list.length?'<section class="card"><h2>Recorded by work type</h2>'+list.map(([work,rows])=>'<div class="total-row"><span>'+esc(work)+'</span><strong>'+rows+' rows</strong></div>').join('')+'<p class="hint">Activity totals — the same physical row may have different work recorded.</p></section>':''}
function yesterday(){const date=new Date(localDay()+'T12:00:00');date.setDate(date.getDate()-1);return localDay(date)}
function needsAttention(){return db.teams.filter(t=>((t.status==='PROBLEM'||t.status==='NOT_COMPLETED')&&!t.issueResolved)||(!t.closed&&t.date<localDay())).sort((a,b)=>b.date.localeCompare(a.date)||a.number-b.number)}
function attentionPanel(){const items=needsAttention();if(!items.length)return '';return '<section class="attention-section"><div class="section-heading"><h2>Needs attention</h2><span class="tag bad">'+items.length+' open</span></div><div class="attention-list">'+items.map(t=>{const flagged=['PROBLEM','NOT_COMPLETED'].includes(t.status)&&!t.issueResolved,label=t.status==='PROBLEM'?'Problem':t.status==='NOT_COMPLETED'?'Not completed':'Open work';return '<article class="card attention-card"><div class="row"><strong>Team '+esc(t.number)+' · '+esc(t.field)+'</strong>'+tag(label,flagged?'PROBLEM':'IN_PROGRESS')+'</div><p>'+esc(t.work)+' · '+dateLabel(t.date)+'</p><p class="muted">'+esc(t.note||(!t.closed?'Work is still open. Record the result or close this team.':'No issue details recorded.'))+'</p><div class="attention-actions">'+btn(t.closed?'View team':'Record work',t.closed?'team':'record','compact',t.id)+(flagged?btn('Resolve','resolveIssue','compact',t.id):'')+'</div></article>'}).join('')+'</div></section>'}
function continueYesterday(){const prior=db.teams.filter(t=>t.date===yesterday()).sort((a,b)=>a.number-b.number);if(!prior.length)return '';return '<section class="continue-section"><div class="section-heading"><h2>Continue from yesterday</h2></div><div class="continue-list">'+prior.map(t=>'<article class="card continue-card"><div><strong>Team '+esc(t.number)+' · '+esc(t.field)+'</strong><p>'+esc(t.work)+' · '+t.members.length+' people · '+esc(rangeText(t))+'</p></div>'+btn('Continue team','continue','compact primary',t.id)+'</article>').join('')+'</div></section>'}
function drawToday(){const t=db.teams.filter(t=>t.date===localDay()),s=staffing();draw(header('Today')+birthdayBanner()+weatherCard()+'<section class="stats stats-actions" aria-label="Today’s staffing"><button type="button" data-action="staffing" data-id="teams" aria-label="Open today’s '+s.teams+' teams"><strong>'+s.teams+'</strong><span>Teams</span></button><button type="button" data-action="staffing" data-id="assigned" aria-label="Open '+s.assigned+' assigned people"><strong>'+s.assigned+'</strong><span>Assigned</span></button><button type="button" data-action="staffing" data-id="available" aria-label="Open '+s.available+' available people"><strong>'+s.available+'</strong><span>Available</span></button></section><p class="hint center">'+s.off+' Off · '+s.sick+' Sick · '+s.active+' active people</p>'+attentionPanel()+summary(t)+'<div class="section-heading"><h2>Today’s teams</h2>'+btn('+ New team','create','small primary')+'</div><div class="team-list" id="today-teams">'+(t.map(card).join('')||empty('No teams today','Your people are ready. Create a team to assign a field, work type and start row.',btn('Create team','create','primary')))+'</div>'+continueYesterday())}
function todayTeams(){return db.teams.filter(t=>t.date===localDay())}
function assignedPeopleIds(){return new Set(todayTeams().filter(t=>!t.closed).flatMap(t=>t.members))}
function availablePeople(){const assigned=assignedPeopleIds();return db.people.filter(p=>p.active&&(p.availability||'ON_SITE')==='ON_SITE'&&!assigned.has(p.id))}
function personAssignmentRow(p,t){return '<button class="person assignment-person" data-action="person" data-id="'+esc(p.id)+'">'+avatar(p)+'<span class="person-copy"><strong>'+esc(p.name)+'</strong><small>Team '+esc(t.number)+' · '+esc(t.field)+' · '+esc(t.work)+'</small><small>'+esc(rangeText(t))+' · '+esc(t.closed?'Closed':labels[t.status]||t.status)+'</small></span>'+tag(t.closed?'Closed':labels[t.status]||t.status,t.status)+'</button>'}
function staffingContent(){const teams=todayTeams();if(staffingMode==='teams')return '<div class="team-list">'+(teams.map(card).join('')||empty('No teams today','Create a team to assign people and work.',btn('Create team','create','primary')))+'</div>';
if(staffingMode==='assigned'){const groups=teams.filter(t=>!t.closed&&t.members.some(id=>person(id))).map(t=>'<section class="card assignment-group"><div class="row"><div><h2>Team '+esc(t.number)+'</h2><p class="assignment-work">'+esc(t.field)+' · '+esc(t.work)+' · '+esc(rangeText(t))+'</p></div>'+tag(labels[t.status]||t.status,t.status)+'</div><div class="list">'+t.members.map(person).filter(Boolean).map(p=>personAssignmentRow(p,t)).join('')+'</div></section>').join('');return groups||empty('Nobody is assigned','Create a team to assign available people.',btn('Create team','create','primary'))}
const available=availablePeople();return available.length?'<form data-form="availableTeam"><p class="muted">Select people, then continue to set the field, work type and start row.</p><section class="card list selection-list">'+available.map(p=>'<label class="select-person"><input type="checkbox" name="member" value="'+esc(p.id)+'">'+avatar(p)+'<span><strong>'+esc(p.name)+'</strong><small>'+esc(p.role)+'</small></span></label>').join('')+'</section><button type="submit" class="primary">Create team with selected</button></form>':empty('No available people','Everyone on site is already assigned. Off and sick employees are shown in People.')}
function drawStaffing(){const title={teams:"Today’s teams",assigned:'Assigned people',available:'Available people'}[staffingMode]||"Today’s staffing";draw(header(title,true)+staffingContent())}
function memberPicker(ids=[],date=localDay(),exclude=''){const groups=db.jobGroups||defaultJobGroups;return '<div class="member-tools"><label>Find a person<input type="search" data-search="members" placeholder="Search full name, role or group" autocomplete="off"></label><label>Job group<select data-filter="member-group"><option value="">All groups</option>'+groups.map(g=>'<option value="'+esc(g)+'">'+esc(g)+'</option>').join('')+'<option value="__none">No group</option></select></label></div><p id="selected-count" class="hint">'+ids.length+' selected · On-site people only</p><div class="member-picker">'+db.people.filter(p=>(p.active&&(p.availability||'ON_SITE')==='ON_SITE')||ids.includes(p.id)).map(p=>{const other=db.teams.filter(t=>t.id!==exclude&&t.date===date&&!t.closed&&t.members.includes(p.id));return '<label class="member-choice" data-person-search="'+esc((p.name+' '+p.role+' '+(p.jobGroup||'')).toLowerCase())+'" data-person-group="'+esc(p.jobGroup||'__none')+'"><input type="checkbox" name="member" value="'+esc(p.id)+'" '+(ids.includes(p.id)?'checked':'')+'>'+avatar(p)+'<span><strong>'+esc(p.name)+'</strong><small>'+esc(p.role)+(p.jobGroup?' · '+esc(p.jobGroup):' · No group')+'</small>'+((!p.active||p.availability==='OFF'||p.availability==='SICK')?'<small class="warning-text">Existing member · '+esc(!p.active?'Archived':availabilityText(p.availability))+'</small>':'')+(other.length?'<small class="warning-text">Assigned to '+other.map(t=>'Team '+t.number).join(', ')+' — confirmation required</small>':'')+'</span></label>'}).join('')+'</div><p id="member-empty" class="hint" hidden>No matching people.</p>'}
function workFields(t={}){return '<div class="grid2"><label>Field<select name="field" required>'+options(db.fields,t.field)+'</select></label><label>Work type<select name="work" required>'+options(db.workTypes,t.work)+'</select></label></div><label>Start row<input name="from" type="number" inputmode="numeric" min="0" max="2147483647" step="1" required value="'+esc(t.from)+'" placeholder="For example, 120"></label>'}
function drawCreate(){draw(header('Create team',true)+(createTemplate?'<p class="muted">Started from yesterday’s Team '+esc(createTemplate.number)+'. Check the crew and update today’s starting row.</p>':'')+(createUnavailable.length?'<p class="hint">Not preselected because they are unavailable, archived, or already assigned today: '+esc(createUnavailable.join(', '))+'.</p>':'')+'<form data-form="create"><section class="card"><h2>Work details</h2>'+workFields(createTemplate||{})+'</section><section class="card"><h2>Team members</h2>'+memberPicker(createMembers)+'</section><p class="hint">Enter the end row after completing the work.</p><button class="primary" type="submit">Create team</button>'+btn('Cancel','back')+'</form>')}
function drawTeam(){const t=team(selected);if(!t){navigate(origin,null,true);return}draw(header('Team '+t.number,true)+'<section class="card"><div class="row"><strong>'+esc(t.field)+'</strong>'+tag(t.closed?'Closed':labels[t.status],t.status)+'</div><h2>'+esc(t.work)+'</h2><p class="muted">'+dateLabel(t.date)+'</p><h2>Team members</h2>'+t.members.map(person).filter(Boolean).map(p=>'<div class="identity">'+avatar(p)+'<span><strong>'+esc(p.name)+'</strong><small>'+esc(p.role)+(p.jobGroup?' · '+esc(p.jobGroup):'')+'</small></span></div>').join('')+'</section><section class="card result"><span>'+esc(rangeText(t))+'</span><strong>'+(isRow(t.to)?actualRows(t)+' rows':'No result recorded')+'</strong><p class="muted">'+(t.note?esc(t.note):'Record the actual work, without a planned target.')+'</p></section>'+(t.closed?btn('Reopen team','reopen','secondary',t.id):btn('Record work','record','primary',t.id))+btn('Edit team','teamEdit','secondary',t.id))}
function drawTeamEdit(){const t=team(selected);snapshot=structuredClone(t);draw(header('Edit team '+t.number,true)+'<form data-form="teamEdit"><section class="card"><label>Date<input name="date" type="date" required value="'+esc(t.date)+'"></label>'+workFields(t)+'</section><section class="card"><h2>Team members</h2>'+memberPicker(t.members,t.date,t.id)+'</section><p class="hint">Changing the start row changes the inclusive recorded total. End row and notes are edited in Record work.</p><button type="submit" class="primary">Save changes</button>'+btn('Cancel','back')+'</form>')}
function drawRecord(){const t=team(selected);snapshot=structuredClone(t);draw(header('Record work',true)+'<section class="card"><h2>Team '+t.number+' · '+esc(t.field)+'</h2><p>'+esc(t.work)+'</p><p class="hint">'+dateLabel(t.date)+'</p></section><form data-form="record"><div class="grid2"><label>Start row<input value="'+t.from+'" readonly aria-readonly="true"></label><label>End row<input type="number" inputmode="numeric" name="to" min="'+t.from+'" max="2147483647" step="1" value="'+esc(t.to)+'" placeholder="Actual end row" aria-describedby="row-preview"></label></div><label class="check-line"><input type="checkbox" name="noOutput" '+(t.status==='NOT_COMPLETED'&&t.to===null?'checked':'')+'> No rows completed</label><div class="card result"><span>Actual completed</span><output id="row-preview">'+(isRow(t.to)?actualRows(t)+' rows':'Enter the end row')+'</output><p class="hint">Both start and end rows are included.</p></div><label>Status<select name="status">'+Object.entries(labels).map(([k,v])=>'<option value="'+k+'" '+(k===t.status?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>Note<textarea name="note" placeholder="Optional details about the work">'+esc(t.note)+'</textarea></label><button type="submit" name="intent" value="progress" class="secondary">Save progress</button><button type="submit" name="intent" value="close" class="primary">Save and close</button>'+btn('Cancel','back')+'</form>')}
function personAssignmentDetails(p){const assigned=assignments(p.id);if(!assigned.length)return '<small>'+esc(!p.active?'Archived':(p.availability||'ON_SITE')==='ON_SITE'?'Available for a team':'Not available')+'</small>';const primary=assigned.find(t=>!t.closed)||assigned[0],extra=assigned.length-1;return '<small class="assignment-main">Team '+esc(primary.number)+' · '+esc(primary.field)+' · '+esc(primary.work)+'</small><small>'+esc(rangeText(primary))+' · '+esc(primary.closed?'Closed':labels[primary.status]||primary.status)+(extra?' · +'+extra+' more today':'')+'</small>'}
function personRows(list){return list.map(p=>{const assigned=assignments(p.id),label=!p.active?'Archived':assigned.length?'Assigned':availabilityText(p.availability),state=!p.active?'ARCHIVED':assigned.length?'IN_PROGRESS':p.availability||'ON_SITE';return '<button class="person" data-action="person" data-id="'+esc(p.id)+'">'+avatar(p)+'<span class="person-copy"><strong>'+esc(p.name)+'</strong><small>'+esc(p.role)+(p.jobGroup?' · '+esc(p.jobGroup):' · No group')+'</small>'+personAssignmentDetails(p)+'</span>'+tag(label,state)+'</button>'}).join('')||empty('No matching people','Try another name or change the filters.')}
function personSearchText(p){return [p.name,p.role,p.jobGroup,...assignments(p.id).flatMap(t=>['team '+t.number,t.field,t.work,rangeText(t)])].join(' ').toLowerCase()}
function filteredPeople(){return db.people.filter(p=>{const assigned=assignments(p.id).length>0,available=p.active&&(p.availability||'ON_SITE')==='ON_SITE'&&!assigned;return (peopleFilter.active==='archived'?!p.active:p.active)&&(!peopleFilter.availability||(p.availability||'ON_SITE')===peopleFilter.availability)&&(!peopleFilter.assignment||(peopleFilter.assignment==='assigned'?assigned:available))&&(!peopleFilter.jobGroup||(peopleFilter.jobGroup==='__none'?!p.jobGroup:p.jobGroup===peopleFilter.jobGroup))&&personSearchText(p).includes(peopleFilter.query.toLowerCase())})}
function peopleResults(){const list=filteredPeople();if(!peopleFilter.grouped)return personRows(list);const groups=[...db.jobGroups,''];return groups.map(group=>{const members=list.filter(p=>(p.jobGroup||'')===group);return '<section class="people-group"><h2>'+esc(group||'No group')+' ('+members.length+')</h2>'+(members.length?personRows(members):'<p class="hint">No employees in this group.</p>')+'</section>'}).join('')}
function drawPeople(){draw(header('People')+'<label class="search-label">Find people<input type="search" data-search="people" value="'+esc(peopleFilter.query)+'" placeholder="Name, role, group, team, field or work"></label><div class="people-filters"><label>Employees<select data-filter="people-active">'+options(['active','archived'],peopleFilter.active)+'</select></label><label>Job group<select data-filter="people-jobGroup"><option value="">All groups</option>'+db.jobGroups.map(g=>'<option value="'+esc(g)+'" '+(peopleFilter.jobGroup===g?'selected':'')+'>'+esc(g)+'</option>').join('')+'<option value="__none" '+(peopleFilter.jobGroup==='__none'?'selected':'')+'>No group</option></select></label><label>Availability<select data-filter="people-availability"><option value="">All statuses</option>'+['ON_SITE','OFF','SICK'].map(s=>'<option value="'+s+'" '+(peopleFilter.availability===s?'selected':'')+'>'+availabilityText(s)+'</option>').join('')+'</select></label><label>Assignment<select data-filter="people-assignment"><option value="">All assignments</option><option value="assigned" '+(peopleFilter.assignment==='assigned'?'selected':'')+'>Assigned today</option><option value="available" '+(peopleFilter.assignment==='available'?'selected':'')+'>Available</option></select></label></div><label class="group-toggle"><input type="checkbox" data-group-people '+(peopleFilter.grouped?'checked':'')+'> Group by job group</label><section class="card list" id="person-list">'+peopleResults()+'</section>'+btn('+ Add person','personNew','primary'))}
function drawPerson(){const p=person(selected);if(!p){navigate('people',null,true);return}const t=assignments(p.id),birthday=birthdayDate(p.birthDate)?'<p class="profile-detail"><strong>Birthday</strong><span>'+birthdayLabel(p.birthDate)+'</span></p>':'';draw(header('Person details',true)+'<section class="card profile-card"><div class="identity">'+avatar(p,'large')+'<div><h2>'+esc(p.name)+'</h2><p class="muted">'+esc(p.role)+'</p></div></div><div class="profile-tags">'+tag(!p.active?'Archived employee':'Active employee',p.active?'ON_SITE':'ARCHIVED')+(p.jobGroup?'<span class="tag group-tag">'+esc(p.jobGroup)+'</span>':'<span class="tag neutral">No group</span>')+tag(availabilityText(p.availability),p.availability||'ON_SITE')+'</div>'+birthday+'</section><h2>Today’s assignment</h2><div class="team-list">'+(t.map(card).join('')||empty('No assignment today',!p.active?'This employee is archived.':(p.availability||'ON_SITE')==='ON_SITE'?'Available for a team.':'Marked '+availabilityText(p.availability)+'.'))+'</div>'+btn('Edit person','personEdit','primary',p.id))}
function photoEditor(p){const preview=pendingPhotoPreview||photoUrls.get(p.id)||'';return '<div class="photo-editor" id="photo-preview">'+(preview?'<span class="avatar profile-photo"><img src="'+esc(preview)+'" alt=""></span>':avatar(p,'profile-photo'))+'<div><label class="photo-button">'+(preview?'Change photo':'Add photo')+'<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" data-photo hidden></label>'+(preview||p.photoPath?btn('Remove photo','removePhoto','photo-remove'):'' )+'<small>Optional · JPG, PNG or WebP · maximum 2 MB</small></div></div>'}
function drawPersonEdit(){const p=screen==='personNew'?{id:pendingId||'',name:'',role:'Technician Solar Panels',jobGroup:'Technicians',photoPath:'',birthDate:'',availability:'ON_SITE',active:true}:person(selected);snapshot=structuredClone(p);draw(header(screen==='personNew'?'Add person':'Edit person',true)+'<form data-form="person"><section class="card">'+photoEditor(p)+'<label>Full name<input name="name" required maxlength="120" value="'+esc(p.name)+'" autocomplete="name"></label><label>Role<input name="role" required maxlength="120" value="'+esc(p.role)+'"></label><label>Birthday <span class="optional">Optional</span><input name="birthDate" type="date" max="'+localDay()+'" value="'+esc(p.birthDate||'')+'"></label><label>Job group<select name="jobGroup"><option value="">No group</option>'+db.jobGroups.map(g=>'<option value="'+esc(g)+'" '+(p.jobGroup===g?'selected':'')+'>'+esc(g)+'</option>').join('')+'</select></label><label>Availability<select name="availability">'+['ON_SITE','OFF','SICK'].map(s=>'<option value="'+s+'" '+((p.availability||'ON_SITE')===s?'selected':'')+'>'+availabilityText(s)+'</option>').join('')+'</select></label><label class="check-line"><input type="checkbox" name="active" '+(p.active?'checked':'')+'> Active employee</label><p class="hint">A birthday reminder appears on Today. Off / Sick means temporarily unavailable. Inactive employees appear under Archived; existing history is kept.</p></section><button class="primary" type="submit">Save person</button>'+btn('Cancel','back')+'</form>')}
function assignmentHistoryResults(){const rows=db.assignmentHistory.filter(a=>{const p=person(a.employeeId);return (!historyFilter.date||a.date===historyFilter.date)&&(!historyFilter.field||a.field===historyFilter.field)&&(!historyFilter.work||a.work===historyFilter.work)&&(!historyFilter.person||p?.name.toLowerCase().includes(historyFilter.person.toLowerCase()))}).sort((a,b)=>b.date.localeCompare(a.date)||(b.startedAt||'').localeCompare(a.startedAt||''));if(!rows.length)return '';return '<section class="card assignment-timeline"><h2>People’s assignment timeline</h2>'+rows.map(a=>'<article class="timeline-row"><div class="timeline-time"><strong>'+(a.startedAt?new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(new Date(a.startedAt)):'Time not recorded')+'</strong><span>'+(a.endedAt?new Intl.DateTimeFormat('en',{hour:'2-digit',minute:'2-digit'}).format(new Date(a.endedAt)):a.active?'Still assigned':'Historical record')+'</span></div><div class="timeline-details"><strong>'+esc(person(a.employeeId)?.name||'Former employee')+' · Team '+esc(a.teamNumber)+'</strong><span>'+esc(a.field)+' · '+esc(a.work)+'</span><small>'+dateLabel(a.date)+' · '+esc(isRow(a.from)?'Start row '+a.from:'')+(a.endReason==='TRANSFERRED'?' · Transferred':a.endReason==='TEAM_CLOSED'?' · Team closed':'')+'</small></div></article>').join('')+'</section>'}
function historyResults(){const list=db.teams.filter(t=>(!historyFilter.date||t.date===historyFilter.date)&&(!historyFilter.field||t.field===historyFilter.field)&&(!historyFilter.work||t.work===historyFilter.work)&&(!historyFilter.person||t.members.some(id=>person(id)?.name.toLowerCase().includes(historyFilter.person.toLowerCase()))||db.assignmentHistory.some(a=>a.teamId===t.id&&person(a.employeeId)?.name.toLowerCase().includes(historyFilter.person.toLowerCase()))));const groups=new Map();for(const t of [...list].sort((a,b)=>b.date.localeCompare(a.date))){if(!groups.has(t.date))groups.set(t.date,[]);groups.get(t.date).push(t)}const teams=list.length?summary(list)+[...groups].map(([d,ts])=>'<h2>'+dateLabel(d)+'</h2><div class="team-list">'+ts.map(historyCard).join('')+'</div>').join(''):'';return assignmentHistoryResults()+teams||empty(db.teams.length?'No matching records':'No records yet',db.teams.length?'Change or clear the filters.':'Your team assignments and recorded work will appear here.',btn(db.teams.length?'Clear filters':'Create team',db.teams.length?'clearHistory':'create','secondary'))}
function drawHistory(){draw(header('History')+'<p class="muted">Assignments and actual work · Open and closed records</p><section class="card filters"><div class="grid2"><label>Date<input type="date" data-filter="history-date" value="'+esc(historyFilter.date)+'"></label><label>Person<input type="search" data-search="history" value="'+esc(historyFilter.person)+'" placeholder="Full name"></label><label>Field<select data-filter="history-field">'+options([...db.fields,...db.teams.map(t=>t.field)],historyFilter.field,'All fields')+'</select></label><label>Work type<select data-filter="history-work">'+options([...db.workTypes,...db.teams.map(t=>t.work)],historyFilter.work,'All work types')+'</select></label></div>'+btn('Clear filters','clearHistory','text-button')+'</section><div id="history-results">'+historyResults()+'</div>')}
function drawSettings(){draw(header('Settings')+'<section class="card list">'+[['fields','Fields',db.fields.join(', ')],['workTypes','Work types',db.workTypes.join(', ')],['jobGroups','Employee groups',db.jobGroups.join(', ')||'No active groups']].map(([k,title,sub])=>'<button class="setting" data-action="directory" data-id="'+k+'"><span><strong>'+title+'</strong><small>'+esc(sub)+'</small></span><span aria-hidden="true">›</span></button>').join('')+'<button class="setting" data-action="nav" data-id="people"><span><strong>People and roles</strong><small>Add, edit and archive employees</small></span><span aria-hidden="true">›</span></button></section><section class="card"><h2>Shared workspace</h2><p>All accounts have equal access.</p><p class="muted">'+esc(user.email)+'</p>'+btn('Team access','access')+'<div id="access-panel"></div></section>'+btn('Sign out','logout'))}
function directoryTitle(){return directory==='fields'?'Fields':directory==='workTypes'?'Work types':'Employee groups'}
function directoryItem(){return directory==='fields'?'field':directory==='workTypes'?'work type':'employee group'}
function drawDirectory(){const groups=directory==='jobGroups',intro=groups?'Groups organize employees independently from their role and today’s team.':'Changes apply to new assignments. Existing records keep their original names.',active=db[directory].map((v,i)=>'<div class="directory-row"><span><strong>'+esc(v)+'</strong>'+(groups?'<small>'+db.people.filter(p=>p.jobGroup===v).length+' employees</small>':'')+'</span><div>'+btn('Edit','editDirectory','compact',i)+btn('Archive','archiveDirectory','compact muted-button',i)+'</div></div>').join('')||'<p class="hint">No active groups.</p>',archived=groups&&db.archivedJobGroups.length?'<h2>Archived groups</h2><section class="card list">'+db.archivedJobGroups.map((v,i)=>'<div class="directory-row"><span><strong>'+esc(v)+'</strong><small>Available to restore</small></span>'+btn('Restore','restoreGroup','compact',i)+'</div>').join('')+'</section>':'';draw(header(directoryTitle(),true)+'<p class="muted">'+intro+'</p><h2>Active '+(groups?'groups':'options')+'</h2><section class="card list">'+active+'</section>'+btn('+ Add '+directoryItem(),'addDirectory','primary')+archived)}
function drawDirectoryEdit(){snapshot=structuredClone(db[directory]);draw(header((directoryIndex<0?'Add ':'Edit ')+directoryItem(),true)+'<form data-form="directory"><section class="card"><label>Name<input name="value" required maxlength="120" value="'+esc(snapshot[directoryIndex]||'')+'"></label><p class="hint">'+(directory==='jobGroups'?'Renaming updates current employee profiles. Roles, teams and history stay unchanged.':'Renaming changes the option for new assignments. Existing records retain the original name.')+'</p></section><button type="submit" class="primary">Save</button>'+btn('Cancel','back')+'</form>')}
function drawAuth(){$('#app').innerHTML=header('Sign in')+'<section class="card auth"><p class="muted">Your team’s shared workspace</p><form data-form="login"><label>Email<input type="email" name="email" required autocomplete="username"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button type="submit" class="primary">Sign in</button></form><div id="feedback" role="alert" tabindex="-1" hidden></div></section>'}
function feedback(message,conflict=false){const el=$('#feedback');if(!el)return;el.hidden=false;el.innerHTML='<p>'+esc(message)+'</p>'+(conflict?'<p class="hint">Your draft remains in the form. Copy any details you need before loading the latest record.</p>'+btn('Load latest record','latest','secondary'):'');el.focus()}
let toastTimer;function toast(message){const el=$('#toast');clearTimeout(toastTimer);el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),5000)}
let lockedInputs=[];function busy(value){saving=value;document.querySelectorAll('button').forEach(b=>b.disabled=value);if(value){lockedInputs=[...document.querySelectorAll('input,select,textarea')].map(el=>[el,el.disabled]);for(const [el]of lockedInputs)el.disabled=true}else{for(const [el,disabled]of lockedInputs)el.disabled=disabled;lockedInputs=[]}const form=$('form');if(form)form.setAttribute('aria-busy',String(value));const label=$('#sync-status');if(label)label.textContent=value?'Saving…':syncText}
async function change(kind,item,expected={}){if(!ready||saving)return false;const actor=user.id;busy(true);try{const {data,error}=await supabase.rpc('solar_change',{kind,item,expected});if(error)throw error;if(user?.id!==actor)return false;acceptRow(data);return true}catch(error){syncText=error.code==='40001'?'Review latest changes before saving':'Not saved · Check connection and retry';feedback(error.code==='40001'?'This record changed on another device. Review the latest version before saving.':'Not saved. Your entries are still here. Check your connection and try again.',error.code==='40001');return false}finally{busy(false)}}
function patchFor(base,values){const item={id:base.id},expected={};for(const [k,v]of Object.entries(values))if(JSON.stringify(base[k]??null)!==JSON.stringify(v)){item[k]=v;expected[k]=base[k]??null}return {item,expected}}
async function patchRecord(kind,base,values){const {item,expected}=patchFor(base,values);if(Object.keys(item).length===1)return true;return change(kind,item,expected)}
async function refreshPhotoUrls(){const entries=db.people.filter(p=>p.photoPath);if(!entries.length){photoUrls=new Map();return}const {data,error}=await supabase.storage.from('employee-photos').createSignedUrls(entries.map(p=>p.photoPath),3600);if(error)return;photoUrls=new Map(entries.map((p,i)=>[p.id,data?.[i]?.signedUrl||'']).filter(([,url])=>url));if(['people','person','team','staffing'].includes(screen))render()}
async function uploadEmployeePhoto(personId,file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG or WebP image.');if(file.size>2*1024*1024)throw new Error('Photo must be 2 MB or smaller.');const ext={"image/jpeg":'jpg',"image/png":'png',"image/webp":'webp'}[file.type],path='people/'+personId+'/'+crypto.randomUUID()+'.'+ext;syncText='Uploading photo…';busy(true);try{const {error}=await supabase.storage.from('employee-photos').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(error)throw error;const {data,error:signedError}=await supabase.storage.from('employee-photos').createSignedUrl(path,3600);if(signedError)throw signedError;return {path,url:data.signedUrl}}finally{busy(false)}}
async function discardPhoto(path){if(path)await supabase.storage.from('employee-photos').remove([path])}
function cachedWeather(){try{const cached=JSON.parse(localStorage.getItem(weatherCacheKey)||'null'),data=normaliseWeather(cached?.data);return data&&Date.now()-Number(cached.fetchedAt)<weatherMaxStaleMs?{data,fetchedAt:Number(cached.fetchedAt)}:null}catch{return null}}
async function loadWeather(force=false){if(!user||!ready||weatherLoading)return;const cached=cachedWeather();if(!force&&cached&&Date.now()-cached.fetchedAt<weatherFreshMs){weather={status:'ready',data:cached.data,fetchedAt:cached.fetchedAt,error:''};if(screen==='today')render();return}
if(cached&&!weather.data)weather={status:'loading',data:cached.data,fetchedAt:cached.fetchedAt,error:''};else weather.status='loading';weatherLoading=true;if(screen==='today')render();try{const {data:authData,error:authError}=await supabase.auth.getSession();const accessToken=authData?.session?.access_token;if(authError||!accessToken)throw new Error('Signed-in session unavailable');const {data,error}=await supabase.functions.invoke('dmi-weather',{method:'GET',headers:{Authorization:`Bearer ${accessToken}`}});if(error)throw error;const parsed=normaliseWeather(data);if(!parsed)throw new Error('Weather response is incomplete');const fetchedAt=Date.now();weather={status:'ready',data:parsed,fetchedAt,error:''};localStorage.setItem(weatherCacheKey,JSON.stringify({data:parsed,fetchedAt}))}catch(error){console.error('DMI weather request failed',{name:error?.name,message:error?.message,status:error?.context?.status});const fallback=weather.data||(cached?.data||null);weather={status:fallback?'stale':'error',data:fallback,fetchedAt:weather.fetchedAt||cached?.fetchedAt||0,error:'Could not refresh from DMI.'}}finally{weatherLoading=false;if(screen==='today'&&user&&ready)render()}}
async function loadCloud(currentUser){user=currentUser;ready=false;accessMessage='Loading shared data…';render();try{const {data,error}=await supabase.from('solar_shared').select('*').eq('id',1).maybeSingle();if(error)throw error;if(!data){accessMessage='Access is by invitation. Ask your workspace administrator for access.';render();return}if(!data.initialized){accessMessage='The shared workspace has not been initialized. Contact your administrator.';render();return}acceptRow(data);render();void loadWeather();void refreshPhotoUrls()}catch{accessMessage='Could not load shared data. Check your connection and retry.';render()}}
async function refreshShared(){if(!user||!ready||saving||dirty||document.hidden||!['today','staffing','people','history','settings','team','person','directory'].includes(screen)||document.activeElement?.matches('input,textarea,select'))return;const actor=user.id;try{const {data,error}=await supabase.from('solar_shared').select('*').eq('id',1).maybeSingle();if(user?.id!==actor||saving||dirty)return;if(error)throw error;if(!data){ready=false;accessMessage='Access to this workspace is unavailable.';render();return}if(data.version>version){acceptRow(data);render();void refreshPhotoUrls()}syncText='Shared data · Up to date';}catch{syncText='Connection lost · Changes must be saved online'}const label=$('#sync-status');if(label)label.textContent=syncText}
async function submitForm(e){e.preventDefault();if(saving)return;const form=e.target,f=new FormData(form),kind=form.dataset.form;$('#feedback')?.setAttribute('hidden','');
if(kind==='login'){busy(true);try{const {data,error}=await supabase.auth.signInWithPassword({email:f.get('email').trim(),password:f.get('password')});if(error)throw error;dirty=false;await loadCloud(data.user)}catch{feedback('Could not sign in. Check your email and password, then try again.')}finally{busy(false)}return}
if(kind==='availableTeam'){const ids=f.getAll('member');if(!ids.length){feedback('Select at least one available person.');return}createMembers=ids;createTemplate=null;createUnavailable=[];createBack='staffing';navigate('create',null,true);return}
if(kind==='create'||kind==='teamEdit'){const from=f.get('from'),ids=f.getAll('member');if(!ids.length||!isRow(from)){feedback('Select at least one person and enter a valid start row.');return}
if(kind==='teamEdit'&&isRow(snapshot.to)&&Number(from)>Number(snapshot.to)){feedback('Start row cannot be after the recorded end row.');return}
const date=kind==='create'?localDay():f.get('date'),conflicts=assignmentConflicts(ids,date,kind==='teamEdit'?snapshot.id:'');let reassign=false;if(conflicts.length){const names=[...new Set(conflicts.flatMap(t=>t.members.filter(id=>ids.includes(id)).map(id=>person(id)?.name)).filter(Boolean))];if(!window.confirm(names.join(', ')+' already assigned to '+conflicts.map(t=>'Team '+t.number).join(', ')+'. Move '+(names.length===1?'this employee':'these employees')+' to the new team?'))return;reassign=true}
const values={members:ids,field:f.get('field'),work:f.get('work'),from:Number(from)};
if(kind==='create'){pendingId ||= crypto.randomUUID();const item={...values,id:pendingId,date,to:null,status:'IN_PROGRESS',note:'',closed:false,issueResolved:false,reassign};if(await change('add_team',item)){createMembers=[];createTemplate=null;createUnavailable=[];createBack='today';navigate('team',item.id,true);toast('Team created for everyone')}}
else{const patch=patchFor(snapshot,{...values,date});if(reassign)patch.item.reassign=true;if(await change('team_patch',patch.item,patch.expected)){navigate('team',selected,true);toast('Team updated for everyone')}}return}
if(kind==='record'){const none=f.get('noOutput')==='on',raw=String(f.get('to')??'').trim(),note=f.get('note').trim(),close=e.submitter?.value==='close';if(!none&&(!isRow(raw)||Number(raw)<Number(snapshot.from))){feedback('Enter an end row of '+snapshot.from+' or higher, or select No rows completed.');return}if(none&&!note){feedback('Add a note explaining why no rows were completed.');return}
let status=none?'NOT_COMPLETED':f.get('status');if(!none&&status==='NOT_COMPLETED'){feedback('Choose another status when rows have been completed.');return}if(close&&['NOT_STARTED','IN_PROGRESS'].includes(status))status='COMPLETED';
if(close&&!window.confirm('Save '+(none?0:actualRows({from:snapshot.from,to:raw}))+' rows and close this team?'))return;
const values={to:none?null:Number(raw),status,note,closed:close,issueResolved:status==='PROBLEM'?false:(snapshot.issueResolved||status!=='PROBLEM')};
if(await patchRecord('team_patch',snapshot,values)){navigate('team',selected,true);toast(close?'Saved and closed for everyone':'Progress saved for everyone')}return}
if(kind==='person'){const isNew=screen==='personNew',personId=isNew?(pendingId ||= crypto.randomUUID()):selected,oldPath=snapshot.photoPath||'';let uploaded=null;const values={name:f.get('name').trim(),role:f.get('role').trim(),birthDate:String(f.get('birthDate')||''),jobGroup:f.get('jobGroup'),availability:f.get('availability'),active:f.get('active')==='on',photoPath:removePhotoRequested?'':oldPath};if(!values.name||!values.role){feedback('Enter a full name and role.');return}if(values.birthDate&&(!birthdayDate(values.birthDate)||values.birthDate>localDay())){feedback('Enter a valid birthday that is not in the future.');return}if(values.jobGroup&&!db.jobGroups.includes(values.jobGroup)){feedback('Choose an active employee group.');return}
try{if(pendingPhotoFile){uploaded=await uploadEmployeePhoto(personId,pendingPhotoFile);values.photoPath=uploaded.path}}catch(error){feedback(error.message||'Photo could not be uploaded. Your other changes are still here.');return}
const saved=isNew?await change('add_person',{id:personId,...values}):await patchRecord('person_patch',snapshot,values);if(!saved){if(uploaded)await discardPhoto(uploaded.path);return}if(oldPath&&oldPath!==values.photoPath)void discardPhoto(oldPath);if(uploaded)photoUrls.set(personId,uploaded.url);else if(!values.photoPath)photoUrls.delete(personId);navigate('person',personId,true);toast(isNew?'Person added':'Person updated for everyone');return}
if(kind==='directory'){const value=f.get('value').trim();if(!value){feedback('Enter a name.');return}if(snapshot.some((v,i)=>i!==directoryIndex&&v.toLowerCase()===value.toLowerCase())||(directory==='jobGroups'&&db.archivedJobGroups.some(v=>v.toLowerCase()===value.toLowerCase()))){feedback('That name already exists.');return}if(directory==='jobGroups'&&directoryIndex>=0){if(await change('job_group_rename',{old:snapshot[directoryIndex],name:value},{jobGroups:snapshot})){navigate('directory',null,true);toast('Employee group renamed for everyone')}return}const values=[...snapshot];if(directoryIndex<0)values.push(value);else values[directoryIndex]=value;
if(await change('settings_patch',{[directory]:values},{[directory]:snapshot})){navigate('directory',null,true);toast('Directory updated for everyone')}}
}
async function act(action,id){if(action==='nav'){navigate(id);return}if(action==='staffing'){staffingMode=id;navigate('staffing');return}if(action==='create'){createMembers=[];createTemplate=null;createUnavailable=[];createBack=screen==='staffing'?'staffing':'today';navigate('create');return}if(action==='continue'){const source=team(id);if(!source||source.date!==yesterday()){toast('Yesterday’s team is no longer available.');return}const nextStart=isRow(source.to)&&Number(source.to)<2147483647?Number(source.to)+1:source.from;createTemplate={number:source.number,field:source.field,work:source.work,from:nextStart};createMembers=source.members.filter(personId=>{const p=person(personId);return p&&p.active&&(p.availability||'ON_SITE')==='ON_SITE'&&assignments(personId).length===0});createUnavailable=source.members.map(person).filter(p=>p&&(!p.active||['OFF','SICK'].includes(p.availability)||assignments(p.id).length>0)).map(p=>p.name);createBack='today';navigate('create');return}if(action==='resolveIssue'){const t=team(id);if(!t||!['PROBLEM','NOT_COMPLETED'].includes(t.status)||t.issueResolved)return;if(await patchRecord('team_patch',t,{issueResolved:true})){render();toast('Issue marked as resolved for everyone')}return}if(action==='person'){personBack=screen;navigate('person',id||null);return}if(['personNew','team','teamEdit','personEdit','record'].includes(action)){if(action==='record'&&team(id)?.closed){toast('Reopen the team before editing its result.');return}navigate(action,id||null);return}
if(action==='back'){if(screen==='create'){createTemplate=null;createUnavailable=[];createMembers=[]}goBack();return}
if(action==='weather'){await loadWeather(true);return}
if(action==='retry'){await loadCloud(user);return}
if(action==='logout'){if(saving||dirty&&!window.confirm('Discard unsaved changes and sign out?'))return;const {error}=await supabase.auth.signOut();if(error){feedback('Could not sign out. Try again.');return}user=null;ready=false;db=structuredClone(seed);weather={status:'idle',data:null,fetchedAt:0,error:''};version=-1;dirty=false;screen='today';render();return}
if(action==='directory'){directory=id;navigate('directory');return}
if(action==='addDirectory'||action==='editDirectory'){directoryIndex=action==='addDirectory'?-1:Number(id);navigate('directoryEdit');return}
if(action==='archiveDirectory'){const values=[...db[directory]],old=values[Number(id)];if(directory!=='jobGroups'&&values.length===1){feedback('Keep at least one active option.');return}const message=directory==='jobGroups'?'Archive "'+old+'"? Employees will move to No group. Their profiles, roles and today’s teams are kept.':'Archive "'+old+'"? It will be hidden for new teams. Existing records are kept.';if(!window.confirm(message))return;if(directory==='jobGroups'){if(await change('job_group_archive',{name:old},{jobGroups:db.jobGroups,archivedJobGroups:db.archivedJobGroups})){render();toast('Group archived; employees moved to No group')}return}values.splice(Number(id),1);if(await change('settings_patch',{[directory]:values},{[directory]:db[directory]})){render();toast('Archived for new assignments')}return}
if(action==='restoreGroup'){const old=db.archivedJobGroups[Number(id)];if(await change('job_group_restore',{name:old},{jobGroups:db.jobGroups,archivedJobGroups:db.archivedJobGroups})){render();toast('Employee group restored')}return}
if(action==='removePhoto'){pendingPhotoFile=null;if(pendingPhotoPreview)URL.revokeObjectURL?.(pendingPhotoPreview);pendingPhotoPreview='';removePhotoRequested=true;dirty=true;const p=screen==='personNew'?{id:'',name:'New person',photoPath:''}:person(selected);$('#photo-preview').outerHTML=photoEditor({...p,photoPath:''});return}
if(action==='clearHistory'){historyFilter={date:'',field:'',work:'',person:''};render();return}
if(action==='reopen'){const t=team(id);if(!window.confirm('Reopen this team for editing?'))return;if(await patchRecord('team_patch',t,{closed:false,status:'IN_PROGRESS'})){render();toast('Team reopened')}return}
if(action==='latest'){if(!window.confirm('Discard this draft and load the latest saved record?'))return;dirty=false;await loadCloud(user);return}
if(action==='access'){try{const {data,error}=await supabase.from('solar_members').select('email').order('added_at');if(error)throw error;$('#access-panel').innerHTML='<h3>Accounts with access</h3>'+data.map(m=>'<p>'+esc(m.email)+' · Full access</p>').join('')}catch{feedback('Could not load workspace accounts. Try again.')}}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!saving)act(b.dataset.action,b.dataset.id).catch(()=>feedback('This action could not finish. Please try again.'))});
document.addEventListener('submit',e=>{if(e.target.matches('form[data-form]'))submitForm(e).catch(()=>{busy(false);feedback('Not saved. Your entries are still here. Please try again.')})});
function filterMemberRows(){const query=$('[data-search="members"]')?.value.toLowerCase()||'',group=$('[data-filter="member-group"]')?.value||'';let visible=0;document.querySelectorAll('[data-person-search]').forEach(row=>{row.hidden=!row.dataset.personSearch.includes(query)||(group&&row.dataset.personGroup!==group);if(!row.hidden)visible++});$('#member-empty').hidden=visible>0}
document.addEventListener('input',e=>{const el=e.target;if(el.dataset.search==='members'){filterMemberRows();return}
if(el.dataset.search==='people'){peopleFilter.query=el.value;$('#person-list').innerHTML=peopleResults();return}
if(el.dataset.search==='history'){historyFilter.person=el.value;$('#history-results').innerHTML=historyResults();return}
if(el.dataset.photo!==undefined){const file=el.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){feedback('Choose a JPG, PNG or WebP image.');el.value='';return}if(file.size>2*1024*1024){feedback('Photo must be 2 MB or smaller.');el.value='';return}if(pendingPhotoPreview)URL.revokeObjectURL?.(pendingPhotoPreview);pendingPhotoFile=file;pendingPhotoPreview=URL.createObjectURL(file);removePhotoRequested=false;dirty=true;const p=screen==='personNew'?{id:'',name:'New person',photoPath:''}:person(selected);$('#photo-preview').outerHTML=photoEditor(p);return}
if(el.closest('form')&&el.name){dirty=true;if(el.name==='member'){const count=$('#selected-count');if(count)count.textContent=document.querySelectorAll('input[name="member"]:checked').length+' selected · On-site people only'}if(['to','noOutput'].includes(el.name)&&screen==='record'){const form=el.closest('form'),none=form.elements.noOutput.checked,to=form.elements.to.value;form.elements.to.disabled=none;$('#row-preview').textContent=none?'0 rows':isRow(to)&&Number(to)>=Number(snapshot.from)?actualRows({from:snapshot.from,to})+' rows':'Enter a valid end row'}}});
document.addEventListener('change',e=>{if(e.target.dataset.groupPeople!==undefined){peopleFilter.grouped=e.target.checked;$('#person-list').innerHTML=peopleResults();return}const f=e.target.dataset.filter;if(!f)return;if(f==='member-group'){filterMemberRows();return}const [group,key]=f.split('-');if(group==='people'){peopleFilter[key]=e.target.value;$('#person-list').innerHTML=peopleResults()}else{historyFilter[key]=e.target.value;$('#history-results').innerHTML=historyResults()}});
window.addEventListener('beforeunload',e=>{if(dirty||saving){e.preventDefault();e.returnValue=''}});
setInterval(refreshShared,5000);setInterval(()=>loadWeather(true),weatherFreshMs);window.addEventListener('focus',refreshShared);window.addEventListener('online',()=>{refreshShared();loadWeather(true)});
if(typeof navigator!=='undefined'&&'serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(session)await loadCloud(session.user);else render()}catch{render();feedback('Could not restore your session. Please sign in again.')}})();
