const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const load=name=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path.join(__dirname,'../'+name),'utf8')).toString('base64'));
function loaderFixture(){const scripts=[],scope={setTimeout,clearTimeout},document={createElement:()=>({remove(){this.removed=true}}),head:{append:script=>scripts.push(script)}};return {scripts,scope,document};}
test('source points become latitude/longitude only with a confirmed projection',async()=>{const m=await load('site-map.js'),proj=require('../vendor/proj4-2.22.0.js');assert.equal(m.sourcePointToLocation([500000,0],null,proj),null);assert.equal(m.sourcePointToLocation([500000,0],'UNKNOWN',proj),null);assert.equal(m.sourcePointToLocation([NaN,0],'EPSG:32632',proj),null);for(const crs of ['EPSG:32632','EPSG:25832']){const p=m.sourcePointToLocation([500000,0],crs,proj);assert.ok(Math.abs(p.lat)<1e-8);assert.ok(Math.abs(p.lng-9)<1e-8)}});
test('Google script loads only on request and concurrent callers share one load',async()=>{const m=await load('google-map.js'),f=loaderFixture(),loader=m.createGoogleMapsLoader({...f,key:'restricted-test-key'});assert.equal(f.scripts.length,0);const a=loader.load(),b=loader.load();assert.equal(a,b);assert.equal(f.scripts.length,1);const url=new URL(f.scripts[0].src);assert.equal(url.origin,'https://maps.googleapis.com');assert.equal(url.searchParams.get('loading'),'async');assert.equal(url.searchParams.get('auth_referrer_policy'),'origin');f.scope.google={maps:{Map:class{}}};f.scope[url.searchParams.get('callback')]();assert.equal(await a,f.scope.google.maps);await loader.load();assert.equal(f.scripts.length,1)});
test('authorization failure is surfaced even after the script callback',async()=>{const m=await load('google-map.js'),f=loaderFixture(),loader=m.createGoogleMapsLoader({...f,key:'test-key'}),failures=[];loader.onFailure(error=>failures.push(error.code));const p=loader.load();f.scope.google={maps:{Map:class{}}};f.scope[new URL(f.scripts[0].src).searchParams.get('callback')]();await p;f.scope.gm_authFailure();assert.deepEqual(failures,['authorization']);await assert.rejects(loader.load(),error=>error.code==='authorization');assert.equal(f.scripts.length,1)});
test('network and timeout failures settle rather than leaving a permanent spinner',async()=>{const m=await load('google-map.js');for(const failure of ['network','timeout']){const f=loaderFixture(),loader=m.createGoogleMapsLoader({...f,key:'test-key',timeoutMs:10}),p=loader.load();if(failure==='network')f.scripts[0].onerror();await assert.rejects(p,error=>error.code===failure);assert.equal(f.scripts[0].removed,true)}});
test('missing configuration does not send an API request',async()=>{const m=await load('google-map.js'),f=loaderFixture(),loader=m.createGoogleMapsLoader({...f,key:''});await assert.rejects(loader.load(),error=>error.code==='configuration');assert.equal(f.scripts.length,0)});

test('Google remount restores the previous camera, while explicit row focus still fits the row',async()=>{
 const {createGoogleSatelliteMap}=await load('google-map.js'),instances=[],options=[],fits=[];
 class FakeMap{constructor(host,opts){options.push(opts);instances.push(this);this.centre=opts.center;this.zoom=opts.zoom;}addListener(){}fitBounds(bounds){fits.push(bounds);}getCenter(){return {lat:()=>this.centre.lat,lng:()=>this.centre.lng};}getZoom(){return this.zoom;}unbindAll(){}}
 class Layer{setMap(){}setOptions(){}addListener(){}}
 const maps={Map:FakeMap,Polyline:Layer,LatLngBounds:class{extend(){}},event:{clearInstanceListeners(){}}},host=()=>({isConnected:true,addEventListener(){}}),row={rowNumber:10,north:[1,2],south:[3,4]},adapter=createGoogleSatelliteMap({loader:{load:async()=>maps,onFailure:()=>()=>{}},toLocation:([lat,lng])=>({lat,lng})});
 adapter.update([row],10,{focus:true});adapter.mount(host());await Promise.resolve();assert.equal(fits.length,1);instances[0].centre={lat:55.46,lng:9.27};instances[0].zoom=19;
 adapter.destroy();adapter.update([row],10);adapter.mount(host());await Promise.resolve();assert.deepEqual(options[1].center,{lat:55.46,lng:9.27});assert.equal(options[1].zoom,19);assert.equal(fits.length,1);
 adapter.update([row],10,{focus:true});assert.equal(fits.length,2);adapter.update([row],null,{resetView:true});adapter.mount(host());await Promise.resolve();assert.equal(options[2].zoom,6);assert.equal(fits.length,3);adapter.destroy();
});
