const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {test}=require('node:test');
const source=readFileSync(require('node:path').resolve(process.env.SOLAR_BASELINE_PATH||require('node:path').join(__dirname,'../app.js')),'utf8').replace(/^import .*$/gm,'');
const featureSource=readFileSync(require('node:path').join(__dirname,'../row-plans.js'),'utf8').replace(/^export /gm,'');
const weatherFunctionSource=readFileSync(require('node:path').join(__dirname,'./fixtures/index.ts'),'utf8');
const peopleUpgradeSource=readFileSync(require('node:path').join(__dirname,'./fixtures/people-groups-photos.sql'),'utf8');
const assignmentUpgradeSource=readFileSync(require('node:path').join(__dirname,'./fixtures/assignment-history-attention.sql'),'utf8');
const workUnitsUpgradeSource=readFileSync(require('node:path').join(__dirname,'./fixtures/20260920120000_work_measurement_units.sql'),'utf8');
const memberRolesUpgradeSource=readFileSync(require('node:path').join(__dirname,'./fixtures/20260922100000_team_member_roles.sql'),'utf8');
const stylesSource=readFileSync(require('node:path').join(__dirname,'../styles.css'),'utf8');
const iconSource=readFileSync(require('node:path').join(__dirname,'../icon.svg'),'utf8');
test('weather function declares its Supabase wrapper exactly once',()=>{
  assert.equal((weatherFunctionSource.match(/import \{ withSupabase \}/g)||[]).length,1);
  assert.match(weatherFunctionSource,/^import 'jsr:@supabase\/functions-js\/edge-runtime\.d\.ts'\r?\nimport \{ withSupabase \}/);
});
test('weather request explicitly forwards the signed-in session token',()=>{
  assert.match(source,/supabase\.auth\.getSession\(\)/);
  assert.match(source,/Authorization:`Bearer \$\{accessToken\}`/);
});
test('weather function keeps live conditions on observations and limits forecast use to precipitation',()=>{
  assert.match(weatherFunctionSource,/\/v2\/metObs\/collections\/observation\/items/);
  assert.match(weatherFunctionSource,/temp_dry/);
  assert.match(weatherFunctionSource,/wind_speed/);
  assert.match(weatherFunctionSource,/forecastedr\/collections\/harmonie_dini_sf\/position/);
  assert.match(weatherFunctionSource,/total-precipitation/);
  assert.match(weatherFunctionSource,/precipitationHours: precipitationMm === null \? null : 6/);
});
function harness(){
  const nodes=new Map();const get=k=>{if(!nodes.has(k))nodes.set(k,{innerHTML:'',textContent:'',hidden:true,disabled:false,classList:{add(){},remove(){}},setAttribute(){},focus(){}});return nodes.get(k)};
  let calls=[],failure=null,confirm=true,cloudRow=null,readQueries=[];
  const client={auth:{getSession:()=>new Promise(()=>{})},rpc:async(name,args)=>{calls.push(args);if(failure)return {error:failure};return {data:{data:JSON.parse(vm.runInContext('JSON.stringify(db)',ctx)),version:2,initialized:true}}}};
  client.from=()=>({select(columns){this.columns=columns;readQueries.push(columns);return this},eq(){return this},maybeSingle:async function(){return {data:this.columns==='version'&&cloudRow?{version:cloudRow.version}:cloudRow}}});
  const document={querySelector:get,querySelectorAll:()=>[],addEventListener(){},hidden:false,activeElement:null};
  class Data{constructor(form){this.values=form.values}get(k){return this.values[k]??null}getAll(k){const v=this.values[k];return Array.isArray(v)?v:v?[v]:[]}}
  const ctx=vm.createContext({createClient:()=>client,document,window:{addEventListener(){},scrollTo(){},confirm:()=>confirm},FormData:Data,structuredClone,console,setInterval(){},setTimeout(){return 1},clearTimeout(){},crypto:{randomUUID:()=> 'new-id'},Date,Intl});
  vm.runInContext(featureSource,ctx);vm.runInContext(source,ctx);
  const run=s=>vm.runInContext(s,ctx);
  run(`user={id:'u',email:'demo@example.test'};ready=true;accessRole='editor';db={people:[{id:'a',name:'Mykola Zihura',role:'Technician',availability:'ON_SITE',active:true},{id:'b',name:'Mykola Yakibchuk',role:'Technician',availability:'ON_SITE',active:true},{id:'c',name:'Off Person',role:'Technician',availability:'OFF',active:true},{id:'d',name:'Archived Person',role:'Technician',availability:'ON_SITE',active:false}],fields:['North'],workTypes:['Panels','Bolts'],assignmentHistory:[],teams:[{id:'t',number:1,date:localDay(),members:['a'],field:'North',work:'Panels',from:120,to:null,status:'IN_PROGRESS',note:'',closed:false,issueResolved:false}]};`);
  return {run,nodes,get,calls,readQueries,cloud:row=>cloudRow=row,fail:e=>failure=e,confirm:v=>confirm=v,submit:async(kind,values,intent)=>{ctx.event={preventDefault(){},target:{dataset:{form:kind},values},submitter:{value:intent}};return run('submitForm(event)')}};
}
test('inclusive rows and missing endpoint never fabricate output',()=>{const h=harness();assert.equal(h.run('actualRows({from:120,to:155})'),36);for(const v of ['null','undefined','""','" "']){assert.equal(h.run(`actualRows({from:0,to:${v}})`),0);assert.equal(h.run(`isRow(${v})`),false)}assert.equal(h.run('actualRows({from:120,to:119})'),0);assert.equal(h.run('isRow(1.5)'),false);assert.equal(h.run('isRow(2147483648)'),false)});
test('work measurement stays backward compatible and adds truck unloading in loads',()=>{const h=harness();const data=JSON.parse(h.run(`JSON.stringify(normalise({workTypes:['Panels'],teams:[{id:'old',work:'Panels',from:10,to:null}]}))`));assert.equal(data.workUnits['Truck unloading'],'loads');assert.equal(data.teams[0].unit,'rows');assert.equal(data.teams[0].quantity,null)});
test('team member roles identify a Manitou driver without changing the person role',async()=>{const h=harness();h.run(`screen='create'`);await h.submit('create',{member:['a','b'],memberRole_a:'Manitou driver',memberRole_b:'Worker',field:'North',work:'Panels',from:'120'});assert.equal(h.calls.length,1);assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0].item.memberRoles)),{a:'Manitou driver'});h.run(`db.teams=[{...db.teams[0],...JSON.parse(${JSON.stringify(JSON.stringify(h.calls[0].item))}),id:'new',number:1}]`);assert.match(h.run(`card(team('new'))`),/Mykola Zihura · Manitou driver/);h.run(`screen='team';selected='new';drawTeam()`);assert.match(h.get('#app').innerHTML,/Manitou driver/)});
test('member roles remain optional for legacy teams',()=>{const h=harness();const data=JSON.parse(h.run(`JSON.stringify(normalise({teams:[{id:'legacy',members:['a'],work:'Panels',from:10,to:null}]}))`));assert.deepEqual(data.teams[0].memberRoles,{});assert.doesNotThrow(()=>h.run(`card(db.teams[0])`))});
test('non-row work creates without row inputs and stores the selected unit',async()=>{const h=harness();h.run(`db.workTypes.push('Truck unloading');db.workUnits={'Truck unloading':'loads'};screen='create'`);const html=h.run(`workFields({work:'Truck unloading'})`);assert.doesNotMatch(html,/name="from"[^>]*required/);await h.submit('create',{member:['a'],field:'North',work:'Truck unloading'});assert.equal(h.calls.length,1);assert.equal(h.calls[0].kind,'add_team');assert.equal(h.calls[0].item.unit,'loads');assert.equal(h.calls[0].item.from,null);assert.equal(h.calls[0].item.to,null)});
test('row work still requires a valid start row',async()=>{const h=harness();h.run(`screen='create'`);await h.submit('create',{member:['a'],field:'North',work:'Panels'});assert.equal(h.calls.length,0)});
test('non-row result saves decimal quantities without inventing a row range',async()=>{const h=harness();h.run(`db.workUnits={'Truck unloading':'loads'};db.workTypes.push('Truck unloading');db.teams[0]={...db.teams[0],work:'Truck unloading',unit:'loads',from:null,to:null,quantity:null};screen='record';selected='t';snapshot=structuredClone(team('t'))`);h.run('drawRecord()');assert.match(h.get('#app').innerHTML,/Actual quantity \(loads\)/);assert.doesNotMatch(h.get('#app').innerHTML,/name="to"|Start row/);await h.submit('record',{quantity:'2.5',note:'',status:'IN_PROGRESS'},'close');assert.equal(h.calls.length,1);assert.equal(h.calls[0].item.quantity,2.5);assert.equal(h.calls[0].item.to,undefined);assert.equal(h.calls[0].item.status,'COMPLETED');assert.equal(h.calls[0].item.closed,true)});
test('non-row zero-output requires a note and saves no quantity',async()=>{const h=harness();h.run(`db.workUnits={'Truck unloading':'loads'};db.teams[0]={...db.teams[0],work:'Truck unloading',unit:'loads',from:null,to:null,quantity:null};screen='record';selected='t';snapshot=structuredClone(team('t'))`);await h.submit('record',{noOutput:'on',note:'',status:'IN_PROGRESS'},'close');assert.equal(h.calls.length,0);await h.submit('record',{noOutput:'on',note:'Truck did not arrive',status:'IN_PROGRESS'},'close');assert.equal(h.calls.length,1);assert.equal(h.calls[0].item.quantity,undefined);assert.equal(h.calls[0].item.to,undefined);assert.equal(h.calls[0].item.status,'NOT_COMPLETED')});
test('non-row summaries and cards show units instead of row numbers',()=>{const h=harness();h.run(`db.workUnits={'Truck unloading':'loads'};const result={id:'load',number:2,date:localDay(),members:['a'],field:'North',work:'Truck unloading',unit:'loads',from:null,to:null,quantity:3,status:'COMPLETED',note:'',closed:true};db.teams.push(result)`);assert.deepEqual(JSON.parse(h.run(`JSON.stringify(totals([team('load')]))`)),[['Truck unloading',3,'loads']]);assert.match(h.run(`card(team('load'))`),/No row range/);assert.match(h.run(`card(team('load'))`),/>3 loads</);assert.doesNotMatch(h.run(`card(team('load'))`),/Start row null|0 rows/)});
test('work type editor persists user-defined units for all accounts',async()=>{const h=harness();h.run(`db.workTypes.push('Truck unloading');db.workUnits={'Truck unloading':'loads'};directory='workTypes';directoryIndex=2;snapshot=structuredClone(db.workTypes);directoryUnitsSnapshot=structuredClone(db.workUnits)`);await h.submit('directory',{value:'Truck unloading',unit:'pallets'});assert.equal(h.calls[0].kind,'settings_patch');assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0].item.workUnits)),{'Truck unloading':'pallets'});assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0].expected.workUnits)),{'Truck unloading':'loads'})});
test('work unit migration updates the shared RPC and retains authenticated-only access',()=>{assert.match(workUnitsUpgradeSource,/Truck unloading/);assert.match(workUnitsUpgradeSource,/'loads'/);assert.match(workUnitsUpgradeSource,/quantity/);assert.match(workUnitsUpgradeSource,/workUnits/);assert.match(workUnitsUpgradeSource,/revoke all on function public\.solar_change/);assert.match(workUnitsUpgradeSource,/grant execute on function public\.solar_change\(text, jsonb, jsonb\) to authenticated/);assert.match(workUnitsUpgradeSource,/begin;/);assert.match(workUnitsUpgradeSource,/commit;/)});
test('member-role migration validates role keys against team members',()=>{assert.match(memberRolesUpgradeSource,/memberRoles/);assert.match(memberRolesUpgradeSource,/jsonb_object_keys/);assert.match(memberRolesUpgradeSource,/not \(item->'members' \? role_id\)/);assert.match(memberRolesUpgradeSource,/grant execute on function public\.solar_change\(text, jsonb, jsonb\) to authenticated/)});
test('staffing distinguishes available, assigned, absent and archived',()=>{const h=harness();assert.deepEqual(JSON.parse(h.run('JSON.stringify(staffing())')),{teams:1,assigned:1,available:1,off:1,sick:0,active:3})});
test('closed teams no longer count people as currently assigned',()=>{const h=harness();h.run(`db.teams[0].closed=true`);assert.deepEqual(JSON.parse(h.run('JSON.stringify(staffing())')),{teams:1,assigned:0,available:2,off:1,sick:0,active:3})});
test('Today shows unresolved problems and overdue open teams until resolved or closed',()=>{const h=harness();h.run(`db.teams=[{id:'problem',number:2,date:yesterday(),members:['a'],field:'North',work:'Bolts',from:140,to:null,status:'PROBLEM',note:'Not enough bolts',closed:true,issueResolved:false},{id:'open',number:3,date:yesterday(),members:['b'],field:'South',work:'Panels',from:200,to:null,status:'IN_PROGRESS',note:'',closed:false,issueResolved:false},{id:'done',number:4,date:yesterday(),members:['b'],field:'South',work:'Panels',from:200,to:205,status:'PROBLEM',note:'Fixed',closed:true,issueResolved:true}]`);assert.deepEqual(Array.from(JSON.parse(h.run('JSON.stringify(needsAttention().map(t=>t.id))'))),['problem','open']);const panel=h.run('attentionPanel()');assert.match(panel,/Not enough bolts/);assert.match(panel,/data-action="resolveIssue"/);assert.doesNotMatch(panel,/Fixed|data-id="done"/) });
test('resolving an issue updates the shared team record',async()=>{const h=harness();h.run(`db.teams[0].status='PROBLEM';db.teams[0].issueResolved=false`);await h.run(`act('resolveIssue','t')`);assert.equal(h.calls.length,1);assert.equal(h.calls[0].kind,'team_patch');assert.equal(h.calls[0].item.issueResolved,true)});
test('continuing yesterday preselects only available employees and advances from the actual end row',async()=>{const h=harness();h.run(`db.teams[0].closed=true;db.teams.push({id:'today-team',number:2,date:localDay(),members:['b'],field:'South',work:'Bolts',from:200,to:null,status:'IN_PROGRESS',note:'',closed:false},{id:'yesterday-team',number:7,date:yesterday(),members:['a','b','c','d'],field:'North',work:'Panels',from:120,to:145,status:'COMPLETED',note:'',closed:true,issueResolved:false})`);assert.match(h.run('continueYesterday()'),/Continue team/);await h.run(`act('continue','yesterday-team')`);assert.deepEqual(Array.from(h.run('createMembers')),['a']);assert.deepEqual(Array.from(h.run('createUnavailable')),['Mykola Yakibchuk','Off Person','Archived Person']);const html=h.get('#app').innerHTML;assert.match(html,/name="from"[^>]*value="146"/);assert.match(html,/value="a" checked/);assert.doesNotMatch(html,/value="b" checked|value="c" checked|value="d" checked/)});
test('assignment timeline preserves transferred employee and both time endpoints',()=>{const h=harness();h.run(`db.assignmentHistory=[{id:'a1',employeeId:'a',teamId:'old-team',teamNumber:1,date:yesterday(),field:'North',work:'Panels',from:120,startedAt:'2026-09-19T06:00:00Z',endedAt:'2026-09-19T10:00:00Z',endReason:'TRANSFERRED',active:false}]`);const html=h.run('historyResults()');assert.match(html,/People’s assignment timeline/);assert.match(html,/Mykola Zihura · Team 1/);assert.match(html,/Transferred/);assert.match(html,/North · Panels/);assert.match(html,/Rows|Start row/)});
test('full surnames in member selection; absent and archived not offered',()=>{const h=harness();const html=h.run('memberPicker()');assert.match(html,/Mykola Zihura/);assert.match(html,/Mykola Yakibchuk/);assert.doesNotMatch(html,/Off Person|Archived Person/)});
test('existing unavailable member remains visible when editing',()=>{const h=harness();assert.match(h.run('memberPicker(["c"])'),/Off Person/)});
test('activity totals are separated',()=>{const h=harness();assert.deepEqual(JSON.parse(h.run(`JSON.stringify(totals([{work:'Panels',from:120,to:155},{work:'Bolts',from:120,to:140}]))`)),[['Panels',36,'rows'],['Bolts',21,'rows']])});
test('archived directory values stay selected on historic teams',()=>{const h=harness();assert.match(h.run(`options(['New'],'Old')`),/value="Old" selected/)});
test('record and close send endpoint, status and close flag in one RPC',async()=>{const h=harness();h.run(`screen='record';selected='t';snapshot=structuredClone(team('t'))`);await h.submit('record',{to:'155',note:'Done',status:'IN_PROGRESS'},'close');assert.equal(h.calls.length,1);const {item,expected}=h.calls[0];assert.equal(item.to,155);assert.equal(item.closed,true);assert.equal(item.status,'COMPLETED');assert.equal(expected.to,null);assert.equal(expected.closed,false)});
test('zero output can close with explanatory note',async()=>{const h=harness();h.run(`screen='record';selected='t';snapshot=structuredClone(team('t'))`);await h.submit('record',{noOutput:'on',note:'Weather',status:'IN_PROGRESS'},'close');assert.equal(h.calls.length,1);assert.equal(h.calls[0].item.status,'NOT_COMPLETED');assert.equal(h.calls[0].item.closed,true);assert.equal(h.calls[0].item.to,undefined)});
test('invalid endpoint and no-output without note cannot save',async()=>{const h=harness();h.run(`screen='record';selected='t';snapshot=structuredClone(team('t'))`);await h.submit('record',{to:'119',note:'',status:'IN_PROGRESS'},'close');await h.submit('record',{to:'',noOutput:'on',note:'',status:'IN_PROGRESS'},'close');assert.equal(h.calls.length,0)});
test('save failure keeps draft and surfaces durable feedback',async()=>{const h=harness();h.fail({code:'network'});h.run(`screen='record';selected='t';snapshot=structuredClone(team('t'));dirty=true`);await h.submit('record',{to:'155',note:'Keep me',status:'IN_PROGRESS'},'progress');assert.equal(h.run('screen'),'record');assert.equal(h.run('dirty'),true);assert.match(h.get('#feedback').innerHTML,/entries are still here/)});
test('concurrency conflict gives explicit latest-record recovery',async()=>{const h=harness();h.fail({code:'40001'});h.run(`screen='record';selected='t';snapshot=structuredClone(team('t'))`);await h.submit('record',{to:'155',note:'',status:'IN_PROGRESS'},'progress');assert.match(h.get('#feedback').innerHTML,/Load latest record/)});
test('cancel leaves dirty form intact',()=>{const h=harness();h.confirm(false);h.run(`screen='record';dirty=true;navigate('today')`);assert.equal(h.run('screen'),'record')});
test('empty history provides an explanation and action',()=>{const h=harness();h.run('db.teams=[]');assert.match(h.run('historyResults()'),/No records yet/);assert.match(h.run('historyResults()'),/Create team/)});
test('names and work types cannot inject HTML',()=>{const h=harness();h.run(`db.people[0].name='<img src=x onerror=alert(1)>'`);assert.doesNotMatch(h.run('personRows(db.people)'),/<img/);assert.match(h.run('personRows(db.people)'),/&lt;img/)});
test('team editing cannot move start beyond saved end',async()=>{const h=harness();h.run(`snapshot=structuredClone(team('t'));snapshot.to=130;selected='t'`);await h.submit('teamEdit',{from:'131',member:['a'],field:'North',work:'Panels',date:'2026-09-19'});assert.equal(h.calls.length,0)});
test('directory rename leaves history untouched and prevents duplicates',async()=>{const h=harness();h.run(`directory='workTypes';directoryIndex=0;snapshot=[...db.workTypes];directoryUnitsSnapshot={}`);await h.submit('directory',{value:'bolts',unit:'rows'});assert.equal(h.calls.length,0);await h.submit('directory',{value:'Panel installation',unit:'rows'});assert.equal(h.calls[0].kind,'settings_patch');assert.deepEqual(Array.from(h.calls[0].item.workTypes),['Panel installation','Bolts']);assert.equal(h.run(`db.teams[0].work`),'Panels')});
test('DMI response validates observations and optional precipitation forecast',()=>{const h=harness();const valid=h.run(`normaliseWeather({weather:{temperatureC:16.9,humidityPct:93,windSpeedMs:8.2,windDirectionDeg:233,precipitationMm:2.4,precipitationHours:6,forecastAt:'2026-09-19T12:00:00Z'}})`);assert.equal(valid.temperatureC,16.9);assert.equal(valid.precipitationMm,2.4);assert.equal(valid.precipitationHours,6);assert.equal(h.run(`normaliseWeather({weather:{temperatureC:999,humidityPct:93,windSpeedMs:8.2,windDirectionDeg:233,forecastAt:'2026-09-19T12:00:00Z'}})`),null)});
test('wind direction uses clear 16-point compass labels',()=>{const h=harness();assert.equal(h.run('windCompass(0)'),'N');assert.equal(h.run('windCompass(44)'),'NE');assert.equal(h.run('windCompass(233)'),'SW');assert.equal(h.run('windCompass(359)'),'N')});
test('compact weather widget omits the oversized site code and keeps site, SVG metrics and rain forecast',()=>{const h=harness();const html=h.run(`weather={status:'ready',data:{temperatureC:16.9,humidityPct:93,windSpeedMs:8.2,windDirectionDeg:233,precipitationMm:2.4,precipitationHours:6,forecastAt:'2026-09-19T12:00:00Z'},fetchedAt:Date.now(),error:''};weatherCard()`);assert.match(html,/Solar Park Nagbøl/);assert.match(html,/Weather at Solar Park Nagbøl/);assert.doesNotMatch(html,/P223_Nagbøl|weather-title|Nagbølvej 83A/);assert.match(html,/16\.9 °C/);assert.match(html,/8\.2 m\/s/);assert.match(html,/Wind · SW 233°/);assert.match(html,/93%/);assert.match(html,/2\.4 mm/);assert.match(html,/Rain · next 6h/);assert.match(html,/<svg/)});
test('Solar Team wordmark and install icon share the sunrise-over-panel mark',()=>{const h=harness();const html=h.run(`header('Today')`);assert.match(html,/class="brand-mark" viewBox="0 0 48 36"/);assert.match(html,/brand-solar">SOLAR/);assert.match(html,/brand-team">TEAM/);assert.match(html,/aria-hidden="true"/);assert.match(iconSource,/viewBox="0 0 192 192"/);assert.match(iconSource,/fill="#152840"/);assert.match(iconSource,/fill="#f0b900"/);assert.match(iconSource,/M28 92h136/)});
test('weather widget retains cached values when refresh fails',()=>{const h=harness();const html=h.run(`weather={status:'stale',data:{temperatureC:12,humidityPct:80,windSpeedMs:4,windDirectionDeg:180,forecastAt:'2026-09-19T10:00:00Z'},fetchedAt:Date.now(),error:'Could not refresh from DMI.'};weatherCard()`);assert.match(html,/Last available observation/);assert.match(html,/Could not refresh from DMI/);assert.match(html,/12\.0 °C/)});
test('today staffing totals are actionable drill-downs',()=>{const h=harness();h.run('drawToday()');const html=h.get('#app').innerHTML;assert.match(html,/data-action="staffing" data-id="teams"/);assert.match(html,/data-action="staffing" data-id="assigned"/);assert.match(html,/data-action="staffing" data-id="available"/)});
test('assigned drill-down groups people with their work location',()=>{const h=harness();h.run(`staffingMode='assigned'`);const html=h.run('staffingContent()');assert.match(html,/Team 1/);assert.match(html,/Mykola Zihura/);assert.match(html,/North/);assert.match(html,/Panels/);assert.match(html,/Start row 120/)});
test('available drill-down can preselect people for a new team',async()=>{const h=harness();await h.submit('availableTeam',{member:['b']});assert.equal(h.run('screen'),'create');assert.deepEqual(Array.from(h.run('createMembers')),['b']);assert.match(h.get('#app').innerHTML,/value="b" checked/)});
test('people list shows assignment context and searches it',()=>{const h=harness();const html=h.run('personRows([db.people[0]])');assert.match(html,/Team 1/);assert.match(html,/North/);assert.match(html,/Panels/);assert.match(html,/Start row 120/);h.run(`peopleFilter.query='north'`);assert.deepEqual(Array.from(h.run('filteredPeople().map(p=>p.id)')),['a'])});
test('people data remains compatible while adding job groups, photos and birthdays',()=>{const h=harness();const data=JSON.parse(h.run(`JSON.stringify(normalise({people:[{id:'a',name:'A Person',role:'Technician',active:true}],fields:[],workTypes:[],teams:[]}))`));assert.deepEqual(data.jobGroups,['Team Leads','Technicians','Mechanics']);assert.deepEqual(data.archivedJobGroups,[]);assert.equal(data.people[0].jobGroup,'');assert.equal(data.people[0].photoPath,'');assert.equal(data.people[0].birthDate,'')});
test('birthday is editable, visible in the profile and announced on Today',()=>{const h=harness();h.run(`db.jobGroups=['Technicians'];db.archivedJobGroups=[];db.people[0].birthDate='1990-09-22';screen='personEdit';selected='a';drawPersonEdit()`);assert.match(h.get('#app').innerHTML,/name="birthDate"/);h.run(`screen='person';drawPerson()`);assert.match(h.get('#app').innerHTML,/September/);assert.match(h.get('#app').innerHTML,/1990/);assert.deepEqual(Array.from(h.run(`birthdaysToday(new Date('2026-09-22T12:00:00')).map(p=>p.id)`)),['a']);h.run("db.people[0].birthDate='1990-'+localDay().slice(5);drawToday()");assert.match(h.get('#app').innerHTML,/Birthday today/);assert.match(h.get('#app').innerHTML,/Mykola Zihura/)});
test('employee avatar uses a signed photo when available and initials otherwise',()=>{const h=harness();h.run(`photoUrls.set('a','https://example.test/a.jpg')`);assert.match(h.run(`avatar(db.people[0],'large')`),/<img/);assert.match(h.run(`avatar(db.people[1])`),/>MY</)});
test('people can be filtered and grouped by job group',()=>{const h=harness();h.run(`db.jobGroups=['Team Leads','Technicians','Mechanics'];db.archivedJobGroups=[];db.people[0].jobGroup='Technicians';db.people[1].jobGroup='Technicians';peopleFilter.jobGroup='Technicians'`);assert.deepEqual(Array.from(h.run('filteredPeople().map(p=>p.id)')),['a','b']);h.run(`peopleFilter.grouped=true`);assert.match(h.run('peopleResults()'),/Technicians \(2\)/)});
test('person editor includes optional photo and job group controls',()=>{const h=harness();h.run(`db.jobGroups=['Team Leads','Technicians','Mechanics'];db.archivedJobGroups=[];db.people[0].photoPath='people/a/photo.jpg';screen='personEdit';selected='a';drawPersonEdit()`);const html=h.get('#app').innerHTML;assert.match(html,/type="file"/);assert.match(html,/name="jobGroup"/);assert.match(html,/Remove photo/)});
test('settings exposes the employee groups directory',()=>{const h=harness();h.run(`db.jobGroups=['Team Leads','Technicians','Mechanics'];db.archivedJobGroups=[];drawSettings()`);assert.match(h.get('#app').innerHTML,/Employee groups/)});
test('Supabase upgrade creates a private photo bucket and workspace-member policies',()=>{assert.match(peopleUpgradeSource,/employee-photos/);assert.match(peopleUpgradeSource,/public\s*=\s*false/);assert.match(peopleUpgradeSource,/solar_private\.is_member\(\)/);assert.match(peopleUpgradeSource,/photoPath/);assert.match(peopleUpgradeSource,/jobGroups/)});
test('assigned employees require confirmation before moving to a new team',async()=>{const h=harness();h.run(`screen='create';createMembers=[]`);h.confirm(false);await h.submit('create',{from:'200',member:['a'],field:'North',work:'Panels'});assert.equal(h.calls.length,0);h.confirm(true);await h.submit('create',{from:'200',member:['a'],field:'North',work:'Panels'});assert.equal(h.calls.length,1);assert.equal(h.calls[0].item.reassign,true)});
test('Supabase upgrade removes reassigned people from other active teams atomically',()=>{assert.match(peopleUpgradeSource,/allow_reassign/);assert.match(peopleUpgradeSource,/Employee already assigned/);assert.match(peopleUpgradeSource,/jsonb_array_elements_text\(team_entry->'members'\)/)});
test('assignment migration backfills legacy teams without fabricated times and keeps RPC invoker security',()=>{assert.match(assignmentUpgradeSource,/legacy:/);assert.match(assignmentUpgradeSource,/'startedAt', null/);assert.match(assignmentUpgradeSource,/'active', not coalesce\(\(team->>'closed'\)::boolean, false\)/);assert.match(assignmentUpgradeSource,/previous_team is null or allow_reassign/);assert.match(assignmentUpgradeSource,/cross join closed_or_updated/);assert.match(assignmentUpgradeSource,/definition := replace\(definition, E'\\r\\n', E'\\n'\);\s*previous := definition/);assert.match(assignmentUpgradeSource,/security invoker/);assert.match(assignmentUpgradeSource,/TRANSFERRED/);assert.match(assignmentUpgradeSource,/issueResolved/);assert.match(assignmentUpgradeSource,/revoke all on function public\.solar_change/);assert.match(assignmentUpgradeSource,/grant execute on function public\.solar_change\(text, jsonb, jsonb\) to authenticated/)});
test('bottom navigation keeps the parent destination active on nested screens',()=>{const h=harness();h.run(`db.jobGroups=['Team Leads','Technicians','Mechanics'];db.archivedJobGroups=[];screen='personEdit';selected='a';drawPersonEdit()`);assert.match(h.get('#app').innerHTML,/data-id="people" aria-current="page"/);h.run(`screen='team';selected='t';origin='history';drawTeam()`);assert.match(h.get('#app').innerHTML,/data-id="history" aria-current="page"/)});
test('bottom navigation has four stable destinations and one current page',()=>{const h=harness();h.run('drawToday()');const html=h.get('#app').innerHTML;assert.equal((html.match(/data-action="nav"/g)||[]).length,4);assert.equal((html.match(/aria-current="page"/g)||[]).length,1);for(const label of ['Today','People','History','Settings'])assert.match(html,new RegExp('>'+label+'<'))});
test('bottom navigation is a contained safe-area dock with a clear active indicator',()=>{assert.match(stylesSource,/\.bottom\{[^}]*width:min\(100%,680px\)/);assert.match(stylesSource,/env\(safe-area-inset-bottom\)/);assert.match(stylesSource,/\.bottom button\[aria-current=page\]::before/);assert.match(stylesSource,/min-height:58px/)});
test('mobile history filters stack and constrain the native date field',()=>{assert.match(stylesSource,/@media\(max-width:420px\)/);assert.match(stylesSource,/\.filters \.grid2\{grid-template-columns:minmax\(0,1fr\)\}/);assert.match(stylesSource,/\.filters input\[type=date\]\{min-width:0;width:100%;max-width:100%;-webkit-appearance:none\}/)});
test('people filters align every label to the same grid baseline',()=>{assert.match(stylesSource,/\.people-filters>label\{[^}]*margin-top:0/);assert.match(stylesSource,/\.people-filters\{[^}]*row-gap:14px/)});
test('bottom navigation icons use individually composed balanced SVG shapes',()=>{const h=harness();for(const key of ['today','people','history','settings']){const svg=h.run(`icon('${key}')`);assert.match(svg,/viewBox="0 0 24 24"/);assert.match(svg,/stroke-width="2"/)}assert.match(h.run(`icon('today')`),/<rect/);assert.match(h.run(`icon('people')`),/<circle/);assert.match(h.run(`icon('settings')`),/M4 21V14/)});

test('common leader appears on every team without exclusive crew assignment or repeated staffing',()=>{const h=harness();h.run("db.people.push({id:'leader',name:'Dimitriy Lysenko',role:'Team leader',active:true,availability:'ON_SITE'});db.defaultTeamLeaderId='leader';db.teams.push({...db.teams[0],id:'t2',number:2,members:['b'],work:'Truck unloading',unit:'loads'});");assert.equal(h.run("assignments('leader').length"),2);assert.equal(h.run('staffing().assigned'),3);assert.deepEqual(Array.from(h.run("assignmentConflicts(['leader']).map(t=>t.id)")),[]);assert.doesNotMatch(h.run("memberPicker()"),/value="leader"/);for(const id of ['t','t2'])assert.match(h.run("card(team('"+id+"'))"),/Team leader · Dimitriy Lysenko/);h.run("screen='create';drawCreate()");assert.match(h.get('#app').innerHTML,/Automatic team leader/)});
test('historical leader snapshot remains independent of the current default',()=>{const h=harness();h.run("db.defaultTeamLeaderId='b';db.teams[0]={...db.teams[0],closed:true,leaderId:'old-leader',leaderName:'Former Leader'}");assert.match(h.run("historyCard(db.teams[0])"),/Former Leader/);assert.doesNotMatch(h.run("historyCard(db.teams[0])"),/Mykola Yakibchuk/)});
test('Settings and row team expose installation plan entry points',()=>{const h=harness();h.run("db.rowPlans=[];db.panelTypes=[];db.jobGroups=[];db.archivedJobGroups=[];screen='settings';drawSettings()");assert.match(h.get('#app').innerHTML,/Row installation plans/);assert.match(h.get('#app').innerHTML,/Description \+ Current Class/);h.run("screen='team';selected='t';drawTeam()");assert.match(h.get('#app').innerHTML,/data-action="teamPlans"/)});
test('automatic leader settings use the protected plan RPC with an optimistic prior ID',async()=>{const h=harness();h.run("db.defaultTeamLeaderId='a';screen='defaultLeader';drawDefaultLeader()");await h.submit('defaultLeader',{employeeId:'b'});assert.equal(h.calls[0].kind,'default_leader_save');assert.equal(h.calls[0].expected.employeeId,'a')});


test('unchanged shared revision polls only the small marker',async()=>{const h=harness();h.run("version=8;screen='today';db=normalise(db)");h.cloud({version:8,data:JSON.parse(h.run('JSON.stringify(db)'))});await h.run('refreshShared()');assert.deepEqual(h.readQueries,['version'])});
test('new shared revision loads the full document once and refreshes the visible record',async()=>{const h=harness();h.run("version=8;screen='today';db=normalise(db)");const remote=JSON.parse(h.run('JSON.stringify(db)'));remote.teams[0].note='Colleague update';h.cloud({version:9,data:remote,initialized:true});await h.run('refreshShared()');assert.deepEqual(h.readQueries,['version','*']);assert.equal(h.run('version'),9);assert.equal(h.run("team('t').note"),'Colleague update')});
test('worker install precaches the exact index and local module URLs',async()=>{const path=require('node:path'),worker=readFileSync(path.join(__dirname,'../service-worker.js'),'utf8'),index=readFileSync(path.join(__dirname,'../index.html'),'utf8');const required=[...index.matchAll(/(?:src|href)="((?:app\.js|styles\.css|row-plans\.css)[^"]*)"/g)].map(m=>'./'+m[1]);const moduleUrl=readFileSync(path.join(__dirname,'../app.js'),'utf8').match(/from '(\.\/row-plans\.js[^']*)'/)[1];required.push(moduleUrl);const listeners={},assets=[];vm.runInNewContext(worker,{self:{addEventListener:(name,fn)=>listeners[name]=fn,skipWaiting:()=>Promise.resolve()},caches:{open:async()=>({addAll:async urls=>assets.push(...urls)})}});let pending;listeners.install({waitUntil:p=>pending=p});await pending;for(const url of required)assert.ok(assets.includes(url),'Cache missing '+url)});


test('viewer can inspect people, teams, history and pallet plans without editing controls',()=>{
 const h=harness();h.run("accessRole='viewer';db=normalise(db);screen='today';drawToday()");
 assert.doesNotMatch(h.get('#app').innerHTML,/data-action="create"/);assert.match(h.get('#app').innerHTML,/Viewing only/);
 h.run("selected='t';screen='team';drawTeam()");assert.doesNotMatch(h.get('#app').innerHTML,/data-action="(record|teamEdit|reopen|resolveIssue)"/);assert.match(h.get('#app').innerHTML,/Row installation plans/);
 h.run("screen='people';drawPeople()");assert.doesNotMatch(h.get('#app').innerHTML,/data-action="personNew"/);assert.match(h.get('#app').innerHTML,/Mykola/);
 h.run("selected='a';screen='person';drawPerson()");assert.doesNotMatch(h.get('#app').innerHTML,/data-action="personEdit"/);
});
test('viewer and unknown role reject direct actions, edit routes and writes before RPC',async()=>{
 const h=harness();h.run("accessRole='viewer';screen='today';db=normalise(db)");
 await h.run("act('create')");assert.equal(h.run('screen'),'today');assert.equal(h.calls.length,0);
 h.run("navigate('personEdit','a',true)");assert.equal(h.run('screen'),'today');
 assert.equal(await h.run("change('team_patch',{id:'t',note:'blocked'},{note:''})"),false);
 await h.submit('person',{name:'Injected',role:'Technician'});assert.equal(h.calls.length,0);
 h.run('accessRole=null');assert.equal(await h.run("change('settings_patch',{}, {})"),false);assert.equal(h.calls.length,0);
});



test('viewer logout affects only this device and an access lookup failure stays closed',async()=>{
 const h=harness();h.run("accessRole='viewer';supabase.auth.signOut=async options=>{globalThis.logoutScope=options.scope;return {}}");
 await h.run("act('logout')");assert.equal(h.run('logoutScope'),'local');assert.equal(h.run('accessRole'),null);
 const denied=harness();denied.run("accessRole='editor';supabase.rpc=async()=>({error:{message:'lookup failed'}})");
 await denied.run("loadCloud(user)");assert.equal(denied.run('accessRole'),null);assert.equal(denied.run('ready'),false);
 assert.equal(await denied.run("change('initialize',{}, {})"),false);assert.equal(denied.calls.length,0);
});


