const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const load=()=>import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync(path.join(__dirname,'../site-map.js'),'utf8')).toString('base64'));
const rows=[{rowNumber:10,field:'South',north:[500000,6100100],south:[500000,6100000]},{rowNumber:11,field:'South',north:[500010,6100075],south:[500010,6100000]}];
function gps(){let success,error,next=0;const started=[],cleared=[];return {started,cleared,emit:p=>success(p),fail:e=>error(e),api:{watchPosition:(ok,bad,options)=>{success=ok;error=bad;started.push(options);return ++next},clearWatch:id=>cleared.push(id)}}}
test('offline cache includes the map module, stylesheet and pinned projection library',async()=>{const vm=require('node:vm'),app=fs.readFileSync(path.join(__dirname,'../app.js'),'utf8'),index=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),worker=fs.readFileSync(path.join(__dirname,'../service-worker.js'),'utf8'),assets=[],listeners={};vm.runInNewContext(worker,{URL,Request,self:{location:{href:'https://example.test/solar-team/service-worker.js'},addEventListener:(name,fn)=>listeners[name]=fn,skipWaiting:()=>Promise.resolve()},caches:{open:async()=>({addAll:async requests=>assets.push(...requests.map(r=>{const u=new URL(r.url);return u.pathname.replace('/solar-team/','./')+u.search;})),match:async()=>({ok:true,text:async()=>index})})}});let pending;listeners.install({waitUntil:p=>pending=p});await pending;const imports=[...app.matchAll(/from '(\.\/[^']+)'/g)].map(m=>m[1]),locals=[...index.matchAll(/(?:src|href)="([^" ]+\.(?:css|js)(?:\?[^" ]*)?)"/g)].map(m=>'./'+m[1]);for(const url of [...imports,...locals])assert.ok(assets.includes(url),'Cache missing '+url);assert.ok(assets.some(url=>url.includes('proj4-2.22.0')))});
test('map bounds and nearest rows use source metres with north up',async()=>{const m=await load(),b=m.mapBounds(rows);assert.ok(b.minE<500000&&b.maxE>500010);assert.ok(b.minN<6100000&&b.maxN>6100100);assert.equal(m.nearestRow([500009,6100050],rows).row.rowNumber,11);assert.equal(m.nearestRow([500000,6100080],rows).distance,0);assert.equal(m.nearestRow([500010,6100090],rows).distance,10);assert.equal(m.nearestRow([NaN,1],rows),null)});
test('projection needs a confirmed CRS and preserves longitude/latitude axis order',async()=>{const m=await load(),proj=require('../vendor/proj4-2.22.0.js');assert.equal(m.projectLocation({latitude:55,longitude:9},null,proj),null);assert.equal(m.projectLocation({latitude:55,longitude:9},'UNKNOWN',proj),null);for(const crs of ['EPSG:32632','EPSG:25832']){const p=m.projectLocation({latitude:0,longitude:9},crs,proj);assert.ok(Math.abs(p[0]-500000)<1e-5);assert.ok(Math.abs(p[1])<1e-5);const dk=m.projectLocation({latitude:55.4,longitude:9.3},crs,proj);assert.ok(dk[0]>510000&&dk[0]<530000);assert.ok(dk[1]>6100000&&dk[1]<6200000)}});
test('geolocation is idle until requested and does not start without map alignment',async()=>{const m=await load(),g=gps(),tracker=m.createLocationTracker({geolocation:g.api,secure:true,aligned:()=>false,onChange:()=>{}});assert.equal(g.started.length,0);tracker.start();assert.equal(g.started.length,0);assert.equal(tracker.state().status,'alignment');tracker.dispose()});
test('live fixes include accuracy, reject invalid data and expire',async()=>{const m=await load(),g=gps();let now=100000;const tracker=m.createLocationTracker({geolocation:g.api,secure:true,aligned:()=>true,now:()=>now,onChange:()=>{}});tracker.start();assert.deepEqual(g.started[0],{enableHighAccuracy:true,maximumAge:0,timeout:15000});g.emit({coords:{latitude:55.4,longitude:9.3,accuracy:7},timestamp:now});assert.equal(tracker.state().fix.accuracy,7);now+=31000;assert.equal(tracker.state().fix,null);g.emit({coords:{latitude:NaN,longitude:9,accuracy:7},timestamp:now});assert.equal(tracker.state().status,'unavailable');assert.equal(tracker.state().fix,null);tracker.dispose();assert.deepEqual(g.cleared,[1])});
test('hidden maps clear watches, discard late callbacks and resume only an enabled session',async()=>{const m=await load(),g=gps(),tracker=m.createLocationTracker({geolocation:g.api,secure:true,aligned:()=>true,onChange:()=>{}});tracker.start();tracker.pause();assert.deepEqual(g.cleared,[1]);g.emit({coords:{latitude:55,longitude:9,accuracy:3},timestamp:Date.now()});assert.equal(tracker.state().fix,null);tracker.resume();assert.equal(g.started.length,2);tracker.stop();tracker.resume();assert.equal(g.started.length,2);assert.deepEqual(g.cleared,[1,2]);tracker.dispose()});
test('permission denial stops; transient GPS failures hide the point and recover on a fresh fix',async()=>{const m=await load(),g=gps(),tracker=m.createLocationTracker({geolocation:g.api,secure:true,aligned:()=>true,onChange:()=>{}});tracker.start();g.fail({code:1});assert.equal(tracker.state().status,'denied');assert.equal(tracker.state().active,false);tracker.start();g.fail({code:3});assert.equal(tracker.state().status,'timeout');assert.equal(tracker.state().active,true);g.fail({code:2});assert.equal(tracker.state().status,'unavailable');assert.equal(tracker.state().fix,null);assert.deepEqual(g.cleared,[1]);g.emit({coords:{latitude:55,longitude:9,accuracy:5},timestamp:Date.now()});assert.equal(tracker.state().status,'watching');assert.equal(tracker.state().fix.accuracy,5);tracker.dispose();assert.deepEqual(g.cleared,[1,2])});
test('unsupported and insecure devices cannot request a watch',async()=>{const m=await load(),g=gps();const unsupported=m.createLocationTracker({secure:true,aligned:()=>true,onChange:()=>{}});unsupported.start();assert.equal(unsupported.state().status,'unsupported');const insecure=m.createLocationTracker({geolocation:g.api,secure:false,aligned:()=>true,onChange:()=>{}});insecure.start();assert.equal(insecure.state().status,'insecure');assert.equal(g.started.length,0)});
test('stale, future and older out-of-order fixes never replace a fresh point',async()=>{const m=await load(),g=gps();let now=100000;const tracker=m.createLocationTracker({geolocation:g.api,secure:true,aligned:()=>true,now:()=>now,onChange:()=>{}});tracker.start();const p=t=>({coords:{latitude:55,longitude:9,accuracy:10},timestamp:t});g.emit(p(now-31000));assert.equal(tracker.state().fix,null);g.emit(p(now+10000));assert.equal(tracker.state().fix,null);g.emit(p(now));g.emit(p(now-1000));assert.equal(tracker.state().fix.timestamp,now);tracker.dispose()});
